// This file is auto-generated by @hey-api/openapi-ts

import { type Options, loginApiLoginPost, logoutApiLogoutPost, fetchCurrentUserApiUsersCurrentGet, getUsersApiUsersGet, getGamesApiGamesHistoryGet } from '../sdk.gen';
import { type MutationOptions, queryOptions } from '@tanstack/svelte-query';
import type { LoginApiLoginPostData, LoginApiLoginPostError, LoginApiLoginPostResponse, LogoutApiLogoutPostData, LogoutApiLogoutPostError, FetchCurrentUserApiUsersCurrentGetData, GetUsersApiUsersGetData, GetGamesApiGamesHistoryGetData } from '../types.gen';
import { client } from '../client.gen';

/**
 * Login
 */
export const loginApiLoginPostMutation = (options?: Partial<Options<LoginApiLoginPostData>>): MutationOptions<LoginApiLoginPostResponse, LoginApiLoginPostError, Options<LoginApiLoginPostData>> => {
    const mutationOptions: MutationOptions<LoginApiLoginPostResponse, LoginApiLoginPostError, Options<LoginApiLoginPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginApiLoginPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const logoutApiLogoutPostMutation = (options?: Partial<Options<LogoutApiLogoutPostData>>): MutationOptions<unknown, LogoutApiLogoutPostError, Options<LogoutApiLogoutPostData>> => {
    const mutationOptions: MutationOptions<unknown, LogoutApiLogoutPostError, Options<LogoutApiLogoutPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutApiLogoutPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const fetchCurrentUserApiUsersCurrentGetQueryKey = (options?: Options<FetchCurrentUserApiUsersCurrentGetData>) => createQueryKey('fetchCurrentUserApiUsersCurrentGet', options);

/**
 * Fetch Current User
 */
export const fetchCurrentUserApiUsersCurrentGetOptions = (options?: Options<FetchCurrentUserApiUsersCurrentGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await fetchCurrentUserApiUsersCurrentGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: fetchCurrentUserApiUsersCurrentGetQueryKey(options)
    });
};

export const getUsersApiUsersGetQueryKey = (options?: Options<GetUsersApiUsersGetData>) => createQueryKey('getUsersApiUsersGet', options);

/**
 * Get Users
 */
export const getUsersApiUsersGetOptions = (options?: Options<GetUsersApiUsersGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUsersApiUsersGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUsersApiUsersGetQueryKey(options)
    });
};

export const getGamesApiGamesHistoryGetQueryKey = (options?: Options<GetGamesApiGamesHistoryGetData>) => createQueryKey('getGamesApiGamesHistoryGet', options);

/**
 * Get Games
 */
export const getGamesApiGamesHistoryGetOptions = (options?: Options<GetGamesApiGamesHistoryGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getGamesApiGamesHistoryGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getGamesApiGamesHistoryGetQueryKey(options)
    });
};
