// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { LoginApiLoginPostData, LoginApiLoginPostResponses, LoginApiLoginPostErrors, LogoutApiLogoutPostData, LogoutApiLogoutPostResponses, LogoutApiLogoutPostErrors, FetchCurrentUserApiUsersCurrentGetData, FetchCurrentUserApiUsersCurrentGetResponses, FetchCurrentUserApiUsersCurrentGetErrors, GetUsersApiUsersGetData, GetUsersApiUsersGetResponses, GetUsersApiUsersGetErrors, GetGamesApiGamesHistoryGetData, GetGamesApiGamesHistoryGetResponses, GetGamesApiGamesHistoryGetErrors, MakeDiceRollApiDiceRollsPostData, MakeDiceRollApiDiceRollsPostResponses, MakeDiceRollApiDiceRollsPostErrors, GetRollByIdApiDiceRollsRollIdGetData, GetRollByIdApiDiceRollsRollIdGetResponses, GetRollByIdApiDiceRollsRollIdGetErrors, SearchIgdbGamesGetApiIgdbGamesSearchGetData, SearchIgdbGamesGetApiIgdbGamesSearchGetResponses, SearchIgdbGamesGetApiIgdbGamesSearchGetErrors } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const loginApiLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiLoginPostData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginApiLoginPostResponses, LoginApiLoginPostErrors, ThrowOnError>({
        url: '/api/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Logout
 */
export const logoutApiLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<LogoutApiLogoutPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutApiLogoutPostResponses, LogoutApiLogoutPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/logout',
        ...options
    });
};

/**
 * Fetch Current User
 */
export const fetchCurrentUserApiUsersCurrentGet = <ThrowOnError extends boolean = false>(options?: Options<FetchCurrentUserApiUsersCurrentGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<FetchCurrentUserApiUsersCurrentGetResponses, FetchCurrentUserApiUsersCurrentGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/users/current',
        ...options
    });
};

/**
 * Get Users
 */
export const getUsersApiUsersGet = <ThrowOnError extends boolean = false>(options?: Options<GetUsersApiUsersGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUsersApiUsersGetResponses, GetUsersApiUsersGetErrors, ThrowOnError>({
        url: '/api/users',
        ...options
    });
};

/**
 * Get Games
 */
export const getGamesApiGamesHistoryGet = <ThrowOnError extends boolean = false>(options?: Options<GetGamesApiGamesHistoryGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetGamesApiGamesHistoryGetResponses, GetGamesApiGamesHistoryGetErrors, ThrowOnError>({
        url: '/api/games-history',
        ...options
    });
};

/**
 * Make Dice Roll
 */
export const makeDiceRollApiDiceRollsPost = <ThrowOnError extends boolean = false>(options: Options<MakeDiceRollApiDiceRollsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<MakeDiceRollApiDiceRollsPostResponses, MakeDiceRollApiDiceRollsPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/dice-rolls',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Roll By Id
 */
export const getRollByIdApiDiceRollsRollIdGet = <ThrowOnError extends boolean = false>(options: Options<GetRollByIdApiDiceRollsRollIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRollByIdApiDiceRollsRollIdGetResponses, GetRollByIdApiDiceRollsRollIdGetErrors, ThrowOnError>({
        url: '/api/dice-rolls/{roll_id}',
        ...options
    });
};

/**
 * Search Igdb Games Get
 */
export const searchIgdbGamesGetApiIgdbGamesSearchGet = <ThrowOnError extends boolean = false>(options: Options<SearchIgdbGamesGetApiIgdbGamesSearchGetData, ThrowOnError>) => {
    return (options.client ?? client).get<SearchIgdbGamesGetApiIgdbGamesSearchGetResponses, SearchIgdbGamesGetApiIgdbGamesSearchGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/igdb/games/search',
        ...options
    });
};
