// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { LoginApiLoginPostData, LoginApiLoginPostResponses, LoginApiLoginPostErrors, LogoutApiLogoutPostData, LogoutApiLogoutPostResponses, LogoutApiLogoutPostErrors, FetchCurrentUserApiUsersCurrentGetData, FetchCurrentUserApiUsersCurrentGetResponses, FetchCurrentUserApiUsersCurrentGetErrors, GetUsersApiUsersGetData, GetUsersApiUsersGetResponses, GetUsersApiUsersGetErrors, GetGamesApiGamesHistoryGetData, GetGamesApiGamesHistoryGetResponses, GetGamesApiGamesHistoryGetErrors, MakeDiceRollApiDiceRollsPostData, MakeDiceRollApiDiceRollsPostResponses, MakeDiceRollApiDiceRollsPostErrors, GetRollByIdApiDiceRollsRollIdGetData, GetRollByIdApiDiceRollsRollIdGetResponses, GetRollByIdApiDiceRollsRollIdGetErrors, SearchIgdbGamesGetApiIgdbGamesSearchGetData, SearchIgdbGamesGetApiIgdbGamesSearchGetResponses, SearchIgdbGamesGetApiIgdbGamesSearchGetErrors, StartIgdbUpdateApiIgdbUpdateStartGetData, StartIgdbUpdateApiIgdbUpdateStartGetResponses, StartIgdbUpdateApiIgdbUpdateStartGetErrors, RefreshStreamsApiStreamsRefreshPostData, RefreshStreamsApiStreamsRefreshPostResponses, RefreshAvatarsApiStreamsRefreshAvatarsPostData, RefreshAvatarsApiStreamsRefreshAvatarsPostResponses, GetGameDurationApiStreamsGameDurationGetData, GetGameDurationApiStreamsGameDurationGetResponses, GetGameDurationApiStreamsGameDurationGetErrors, CloseGameCategoriesApiStreamsCloseGameCategoriesPostData, CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponses, CloseGameCategoriesApiStreamsCloseGameCategoriesPostErrors, GetEventsApiEventsGetData, GetEventsApiEventsGetResponses, SearchEmotesApiEmotesSearchPostData, SearchEmotesApiEmotesSearchPostResponses, SearchEmotesApiEmotesSearchPostErrors } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const loginApiLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiLoginPostData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginApiLoginPostResponses, LoginApiLoginPostErrors, ThrowOnError>({
        url: '/api/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Logout
 */
export const logoutApiLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<LogoutApiLogoutPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutApiLogoutPostResponses, LogoutApiLogoutPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/logout',
        ...options
    });
};

/**
 * Fetch Current User
 */
export const fetchCurrentUserApiUsersCurrentGet = <ThrowOnError extends boolean = false>(options?: Options<FetchCurrentUserApiUsersCurrentGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<FetchCurrentUserApiUsersCurrentGetResponses, FetchCurrentUserApiUsersCurrentGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/users/current',
        ...options
    });
};

/**
 * Get Users
 */
export const getUsersApiUsersGet = <ThrowOnError extends boolean = false>(options?: Options<GetUsersApiUsersGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUsersApiUsersGetResponses, GetUsersApiUsersGetErrors, ThrowOnError>({
        url: '/api/users',
        ...options
    });
};

/**
 * Get Games
 */
export const getGamesApiGamesHistoryGet = <ThrowOnError extends boolean = false>(options?: Options<GetGamesApiGamesHistoryGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetGamesApiGamesHistoryGetResponses, GetGamesApiGamesHistoryGetErrors, ThrowOnError>({
        url: '/api/games-history',
        ...options
    });
};

/**
 * Make Dice Roll
 */
export const makeDiceRollApiDiceRollsPost = <ThrowOnError extends boolean = false>(options: Options<MakeDiceRollApiDiceRollsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<MakeDiceRollApiDiceRollsPostResponses, MakeDiceRollApiDiceRollsPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/dice-rolls',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Roll By Id
 */
export const getRollByIdApiDiceRollsRollIdGet = <ThrowOnError extends boolean = false>(options: Options<GetRollByIdApiDiceRollsRollIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetRollByIdApiDiceRollsRollIdGetResponses, GetRollByIdApiDiceRollsRollIdGetErrors, ThrowOnError>({
        url: '/api/dice-rolls/{roll_id}',
        ...options
    });
};

/**
 * Search Igdb Games Get
 */
export const searchIgdbGamesGetApiIgdbGamesSearchGet = <ThrowOnError extends boolean = false>(options: Options<SearchIgdbGamesGetApiIgdbGamesSearchGetData, ThrowOnError>) => {
    return (options.client ?? client).get<SearchIgdbGamesGetApiIgdbGamesSearchGetResponses, SearchIgdbGamesGetApiIgdbGamesSearchGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/igdb/games/search',
        ...options
    });
};

/**
 * Start Igdb Update
 */
export const startIgdbUpdateApiIgdbUpdateStartGet = <ThrowOnError extends boolean = false>(options?: Options<StartIgdbUpdateApiIgdbUpdateStartGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<StartIgdbUpdateApiIgdbUpdateStartGetResponses, StartIgdbUpdateApiIgdbUpdateStartGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/igdb/update/start',
        ...options
    });
};

/**
 * Refresh Streams
 * Refresh stream statuses for all active streamers.
 *
 * Returns statistics about the refresh operation:
 * - total_players: Total number of active players checked
 * - updated_players: Number of players whose status changed
 * - online_players: Number of players currently online
 * - errors: List of error messages if any occurred
 */
export const refreshStreamsApiStreamsRefreshPost = <ThrowOnError extends boolean = false>(options?: Options<RefreshStreamsApiStreamsRefreshPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<RefreshStreamsApiStreamsRefreshPostResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/streams/refresh',
        ...options
    });
};

/**
 * Refresh Avatars
 * Refresh avatars for all users with main platform and stream link.
 *
 * Returns statistics about the refresh operation:
 * - total_users: Total number of users checked
 * - updated_users: Number of users whose avatar was updated
 * - errors: List of error messages if any occurred
 */
export const refreshAvatarsApiStreamsRefreshAvatarsPost = <ThrowOnError extends boolean = false>(options?: Options<RefreshAvatarsApiStreamsRefreshAvatarsPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<RefreshAvatarsApiStreamsRefreshAvatarsPostResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/streams/refresh-avatars',
        ...options
    });
};

/**
 * Get Game Duration
 * Get total duration of all open categories for a specific game within active event.
 *
 * Used by aukus-backend when creating a player move to calculate item_duration.
 *
 * Returns:
 * - duration: Total seconds of all open category sessions
 * - sessions_count: Number of open sessions
 * - event_slug: Slug of the active event (if any)
 */
export const getGameDurationApiStreamsGameDurationGet = <ThrowOnError extends boolean = false>(options: Options<GetGameDurationApiStreamsGameDurationGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetGameDurationApiStreamsGameDurationGetResponses, GetGameDurationApiStreamsGameDurationGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/streams/game-duration',
        ...options
    });
};

/**
 * Close Game Categories
 * Close all open categories for a specific game within active event.
 *
 * Called by aukus-backend after creating a player move to mark the game session as complete.
 * This ensures that if the player starts the same game again, the timer resets.
 *
 * Request body:
 * - slug: User slug
 * - game_name: Name of the game to close categories for
 *
 * Returns:
 * - status: Operation status
 * - closed: Number of categories closed
 * - game_name: Name of the game
 * - event_slug: Slug of the active event (if any)
 */
export const closeGameCategoriesApiStreamsCloseGameCategoriesPost = <ThrowOnError extends boolean = false>(options: Options<CloseGameCategoriesApiStreamsCloseGameCategoriesPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponses, CloseGameCategoriesApiStreamsCloseGameCategoriesPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/streams/close-game-categories',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Events
 */
export const getEventsApiEventsGet = <ThrowOnError extends boolean = false>(options?: Options<GetEventsApiEventsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEventsApiEventsGetResponses, unknown, ThrowOnError>({
        url: '/api/events',
        ...options
    });
};

/**
 * Search Emotes
 */
export const searchEmotesApiEmotesSearchPost = <ThrowOnError extends boolean = false>(options: Options<SearchEmotesApiEmotesSearchPostData, ThrowOnError>) => {
    return (options.client ?? client).post<SearchEmotesApiEmotesSearchPostResponses, SearchEmotesApiEmotesSearchPostErrors, ThrowOnError>({
        url: '/api/emotes/search',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
