// This file is auto-generated by @hey-api/openapi-ts

/**
 * AvatarRefreshStats
 */
export type AvatarRefreshStats = {
    /**
     * Total Users
     */
    total_users: number;
    /**
     * Updated Users
     */
    updated_users: number;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * CloseGameCategoriesRequest
 */
export type CloseGameCategoriesRequest = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Game Name
     */
    game_name: string;
};

/**
 * CloseGameCategoriesResponse
 */
export type CloseGameCategoriesResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Closed
     */
    closed: number;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Event Slug
     */
    event_slug?: string | null;
    /**
     * Game Name
     */
    game_name?: string | null;
};

/**
 * DiceRollRequest
 */
export type DiceRollRequest = {
    dice: DiceType;
    /**
     * Used
     */
    used?: boolean;
    /**
     * Test Values
     */
    test_values?: Array<number>;
};

/**
 * DiceRollResponse
 */
export type DiceRollResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: number;
    /**
     * User Slug
     */
    user_slug: string;
    /**
     * Is Used
     */
    is_used: boolean;
    dice_type: DiceType;
    /**
     * Roll Values
     */
    roll_values: Array<number>;
    /**
     * Is Random Org Result
     */
    is_random_org_result: boolean;
    /**
     * Random Org Check Url
     */
    random_org_check_url: string | null;
    /**
     * Random Org Fail Reason
     */
    random_org_fail_reason: string | null;
};

/**
 * DiceType
 */
export type DiceType = '1d2' | '1d4' | '2d4' | '3d4' | '1d6' | '2d6' | '3d6' | '4d6' | '1d8' | '2d8';

/**
 * EmoteItem
 */
export type EmoteItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Owner Username
     */
    owner_username: string | null;
    /**
     * Listed
     */
    listed: boolean;
    /**
     * Cdn Url
     */
    cdn_url: string;
};

/**
 * EmoteSearchRequest
 */
export type EmoteSearchRequest = {
    /**
     * Search Term
     */
    search_term?: string;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Page
     */
    page?: number;
};

/**
 * EmoteSearchResponse
 */
export type EmoteSearchResponse = {
    /**
     * Emotes
     */
    emotes: Array<EmoteItem>;
};

/**
 * EventItem
 */
export type EventItem = {
    /**
     * Organizer Id
     */
    organizer_id: number;
    /**
     * Slug
     */
    slug: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Start Timestamp
     */
    start_timestamp: number;
    /**
     * End Timestamp
     */
    end_timestamp: number | null;
    /**
     * Participants
     */
    participants: Array<EventParticipantItem>;
    /**
     * Link
     */
    link: string | null;
    /**
     * Banner Url
     */
    banner_url: string;
    /**
     * Logo Url
     */
    logo_url: string;
    /**
     * Developer Slug
     */
    developer_slug: string;
};

/**
 * EventParticipantItem
 */
export type EventParticipantItem = {
    /**
     * User Slug
     */
    user_slug: string;
    /**
     * Placement
     */
    placement: number | null;
};

/**
 * EventsResponse
 */
export type EventsResponse = {
    /**
     * Events
     */
    events: Array<EventItem>;
};

/**
 * GameCompletionStatus
 */
export type GameCompletionStatus = 'completed' | 'reroll' | 'drop';

/**
 * GameDifficulty
 */
export type GameDifficulty = 'easy' | 'normal' | 'hard' | 'very-hard';

/**
 * GameDurationResponse
 */
export type GameDurationResponse = {
    /**
     * Duration
     */
    duration: number;
    /**
     * Sessions Count
     */
    sessions_count: number;
    /**
     * Event Slug
     */
    event_slug: string;
};

/**
 * GameHistoryItem
 */
export type GameHistoryItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Player Nickname
     */
    player_nickname: string;
    /**
     * Event Name
     */
    event_name: string;
    /**
     * Game Title
     */
    game_title: string;
    /**
     * Game Cover
     */
    game_cover: string;
    /**
     * Game Link
     */
    game_link: string;
    /**
     * Game Year
     */
    game_year: number | null;
    completion_status: GameCompletionStatus;
    difficulty?: GameDifficulty | null;
    /**
     * Date
     */
    date: string;
    /**
     * Review
     */
    review: string;
    /**
     * Rating
     */
    rating: string;
    /**
     * Game Time
     */
    game_time: number;
    /**
     * Hltb Id
     */
    hltb_id: number | null;
    /**
     * Igdb Id
     */
    igdb_id: number | null;
    /**
     * Steam Id
     */
    steam_id: number | null;
};

/**
 * GamesHistoryResponse
 */
export type GamesHistoryResponse = {
    /**
     * Games
     */
    games: Array<GameHistoryItem>;
    /**
     * Next Id
     */
    next_id: number | null;
};

/**
 * GamesHistoryStatsResponse
 */
export type GamesHistoryStatsResponse = {
    /**
     * Players
     */
    players: Array<PlayerStatsItem>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HepegaAuction
 */
export type HepegaAuction = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title?: string;
    /**
     * Mode
     */
    mode?: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Wheel Winner Id
     */
    wheel_winner_id?: string | null;
    /**
     * Wheel Spin Active
     */
    wheel_spin_active?: boolean;
};

/**
 * HepegaLot
 */
export type HepegaLot = {
    /**
     * Id
     */
    id: string;
    /**
     * Lot Number
     */
    lot_number: number;
    /**
     * Name
     */
    name: string;
    /**
     * Amount
     */
    amount?: number;
    /**
     * Is Winner
     */
    is_winner?: boolean;
};

/**
 * HepegaState
 */
export type HepegaState = {
    /**
     * Server Now Ms
     */
    server_now_ms?: number;
    auction: HepegaAuction;
    timer: HepegaTimer;
    /**
     * Lots
     */
    lots?: Array<HepegaLot>;
};

/**
 * HepegaTimer
 */
export type HepegaTimer = {
    /**
     * Status
     */
    status?: string;
    /**
     * Mode
     */
    mode?: string;
    /**
     * Ends At Ms
     */
    ends_at_ms?: number | null;
    /**
     * Remaining Ms
     */
    remaining_ms?: number;
    /**
     * Elapsed Ms
     */
    elapsed_ms?: number;
    /**
     * Total Elapsed Ms
     */
    total_elapsed_ms?: number;
};

/**
 * HltbGameResponse
 */
export type HltbGameResponse = {
    /**
     * Game Id
     */
    game_id: number;
    /**
     * Game Name
     */
    game_name: string;
    /**
     * Game Name Date
     */
    game_name_date: number;
    /**
     * Game Alias
     */
    game_alias?: string | null;
    /**
     * Game Type
     */
    game_type: string;
    /**
     * Game Image
     */
    game_image: string;
    /**
     * Comp Lvl Combine
     */
    comp_lvl_combine: number;
    /**
     * Comp Lvl Sp
     */
    comp_lvl_sp: number;
    /**
     * Comp Lvl Co
     */
    comp_lvl_co: number;
    /**
     * Comp Lvl Mp
     */
    comp_lvl_mp: number;
    /**
     * Comp Main
     */
    comp_main: number;
    /**
     * Comp Plus
     */
    comp_plus: number;
    /**
     * Comp 100
     */
    comp_100: number;
    /**
     * Comp All
     */
    comp_all: number;
    /**
     * Comp Main Count
     */
    comp_main_count: number;
    /**
     * Comp Plus Count
     */
    comp_plus_count: number;
    /**
     * Comp 100 Count
     */
    comp_100_count: number;
    /**
     * Comp All Count
     */
    comp_all_count: number;
    /**
     * Invested Co
     */
    invested_co: number;
    /**
     * Invested Mp
     */
    invested_mp: number;
    /**
     * Invested Co Count
     */
    invested_co_count: number;
    /**
     * Invested Mp Count
     */
    invested_mp_count: number;
    /**
     * Count Comp
     */
    count_comp: number;
    /**
     * Count Speedrun
     */
    count_speedrun: number;
    /**
     * Count Backlog
     */
    count_backlog: number;
    /**
     * Count Review
     */
    count_review: number;
    /**
     * Review Score
     */
    review_score: number;
    /**
     * Count Playing
     */
    count_playing: number;
    /**
     * Count Retired
     */
    count_retired: number;
    /**
     * Profile Platform
     */
    profile_platform?: string | null;
    /**
     * Profile Popular
     */
    profile_popular: number;
    /**
     * Release World
     */
    release_world?: number | null;
    /**
     * Genres
     */
    genres?: string | null;
    /**
     * Steam Id
     */
    steam_id?: number | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
};

/**
 * HltbGamesListResponse
 */
export type HltbGamesListResponse = {
    /**
     * Games
     */
    games: Array<HltbGameResponse>;
};

/**
 * IgdbGameSummary
 */
export type IgdbGameSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Cover
     */
    cover?: string | null;
    /**
     * Release Year
     */
    release_year?: number | null;
};

/**
 * IgdbGamesListResponse
 */
export type IgdbGamesListResponse = {
    /**
     * Games
     */
    games: Array<IgdbGameSummary>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Token
     */
    token: string;
};

/**
 * NassalStreamerItem
 */
export type NassalStreamerItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is Online
     */
    is_online: number;
    /**
     * Online Count
     */
    online_count: number;
    /**
     * Main Platform
     */
    main_platform: string;
    /**
     * Twitch Stream Link
     */
    twitch_stream_link?: string | null;
    /**
     * Vk Stream Link
     */
    vk_stream_link?: string | null;
    /**
     * Kick Stream Link
     */
    kick_stream_link?: string | null;
};

/**
 * NassalStreamsResponse
 */
export type NassalStreamsResponse = {
    /**
     * Streamers
     */
    streamers: Array<NassalStreamerItem>;
    /**
     * Checked At
     */
    checked_at: number;
};

/**
 * OAuthAuthorizeRequest
 */
export type OAuthAuthorizeRequest = {
    /**
     * Provider Name
     */
    provider_name: string;
    /**
     * Event Name
     */
    event_name: string;
};

/**
 * OAuthAuthorizeResponse
 */
export type OAuthAuthorizeResponse = {
    /**
     * Authorization Url
     */
    authorization_url: string;
    /**
     * State
     */
    state: string;
};

/**
 * OAuthCallbackRequest
 */
export type OAuthCallbackRequest = {
    /**
     * Provider Name
     */
    provider_name: string;
    /**
     * Code
     */
    code: string;
    /**
     * State
     */
    state: string;
};

/**
 * OAuthCallbackResponse
 */
export type OAuthCallbackResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * OAuthIntegrationInfo
 */
export type OAuthIntegrationInfo = {
    /**
     * Provider Name
     */
    provider_name: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Has Refresh Token
     */
    has_refresh_token: boolean;
    /**
     * Expires At
     */
    expires_at: number | null;
};

/**
 * OAuthIntegrationsResponse
 */
export type OAuthIntegrationsResponse = {
    /**
     * Integrations
     */
    integrations: Array<OAuthIntegrationInfo>;
};

/**
 * OAuthProviderInfo
 */
export type OAuthProviderInfo = {
    /**
     * Provider Name
     */
    provider_name: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Scopes
     */
    scopes: string;
};

/**
 * OAuthProvidersResponse
 */
export type OAuthProvidersResponse = {
    /**
     * Providers
     */
    providers: Array<OAuthProviderInfo>;
};

/**
 * OAuthRefreshRequest
 */
export type OAuthRefreshRequest = {
    /**
     * Provider Name
     */
    provider_name: string;
};

/**
 * OAuthRefreshResponse
 */
export type OAuthRefreshResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * PlayerMoveNotificationRequest
 */
export type PlayerMoveNotificationRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Move Type
     */
    move_type: string;
    /**
     * Item Title
     */
    item_title: string;
    /**
     * Item Review
     */
    item_review: string;
    /**
     * Item Rating
     */
    item_rating: number | null;
    /**
     * Cell From
     */
    cell_from: number;
    /**
     * Cell To
     */
    cell_to: number;
    /**
     * Dice Roll Sum
     */
    dice_roll_sum?: number | null;
    /**
     * Game Id
     */
    game_id?: number | null;
    /**
     * Cover Image Url
     */
    cover_image_url?: string | null;
    /**
     * Item Duration
     */
    item_duration?: number;
    /**
     * Snake
     */
    snake?: number | null;
    /**
     * Ladder
     */
    ladder?: number | null;
};

/**
 * PlayerOnlineNotificationRequest
 */
export type PlayerOnlineNotificationRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Game Name
     */
    game_name?: string | null;
    /**
     * Stream Url
     */
    stream_url?: string | null;
    /**
     * Thumbnail Url
     */
    thumbnail_url?: string | null;
};

/**
 * PlayerStatsItem
 */
export type PlayerStatsItem = {
    /**
     * Player Nickname
     */
    player_nickname: string;
    /**
     * Events
     */
    events: {
        [key: string]: number;
    };
};

/**
 * SendNotificationRequest
 */
export type SendNotificationRequest = {
    /**
     * Message
     */
    message: string;
    /**
     * Parse Mode
     */
    parse_mode?: string;
};

/**
 * StreamRefreshStats
 */
export type StreamRefreshStats = {
    /**
     * Total Players
     */
    total_players: number;
    /**
     * Updated Players
     */
    updated_players: number;
    /**
     * Online Players
     */
    online_players: number;
    /**
     * Errors
     */
    errors: Array<string>;
};

/**
 * UserItem
 */
export type UserItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Slug
     */
    slug: string;
    /**
     * Username
     */
    username: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Roles
     */
    roles: Array<UserRole>;
    /**
     * Moder For
     */
    moder_for: Array<string>;
    /**
     * Is Active
     */
    is_active: number;
    /**
     * Is Online
     */
    is_online?: number;
    /**
     * Current Game
     */
    current_game?: string | null;
    /**
     * Current Game Cover
     */
    current_game_cover?: string | null;
    /**
     * Current Game Updated At
     */
    current_game_updated_at?: number | null;
    /**
     * Current Game Duration
     */
    current_game_duration?: number;
    /**
     * Online Count
     */
    online_count?: number;
    /**
     * Completed Game Name
     */
    completed_game_name?: string | null;
    /**
     * Completed Game Event Id
     */
    completed_game_event_id?: number | null;
    /**
     * Main Platform
     */
    main_platform: string | null;
    /**
     * Twitch Stream Link
     */
    twitch_stream_link: string | null;
    /**
     * Vk Stream Link
     */
    vk_stream_link: string | null;
    /**
     * Kick Stream Link
     */
    kick_stream_link: string | null;
    /**
     * Telegram Link
     */
    telegram_link: string | null;
    /**
     * Donation Link
     */
    donation_link: string | null;
    /**
     * Avatar Link
     */
    avatar_link: string | null;
    /**
     * Color
     */
    color: string | null;
    hepega_auc_state?: HepegaState | null;
};

/**
 * UserRole
 */
export type UserRole = 'streamer' | 'admin' | 'rules.edit';

/**
 * UsersResponse
 */
export type UsersResponse = {
    /**
     * Users
     */
    users: Array<UserItem>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type TestExceptionApiTestExceptionGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test/exception';
};

export type TestExceptionApiTestExceptionGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginApiLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LoginApiLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiLoginPostError = LoginApiLoginPostErrors[keyof LoginApiLoginPostErrors];

export type LoginApiLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiLoginPostResponse = LoginApiLoginPostResponses[keyof LoginApiLoginPostResponses];

export type LogoutApiLogoutPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/logout';
};

export type LogoutApiLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiLogoutPostError = LogoutApiLogoutPostErrors[keyof LogoutApiLogoutPostErrors];

export type LogoutApiLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FetchCurrentUserApiUsersCurrentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/users/current';
};

export type FetchCurrentUserApiUsersCurrentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FetchCurrentUserApiUsersCurrentGetError = FetchCurrentUserApiUsersCurrentGetErrors[keyof FetchCurrentUserApiUsersCurrentGetErrors];

export type FetchCurrentUserApiUsersCurrentGetResponses = {
    /**
     * Successful Response
     */
    200: UserItem;
};

export type FetchCurrentUserApiUsersCurrentGetResponse = FetchCurrentUserApiUsersCurrentGetResponses[keyof FetchCurrentUserApiUsersCurrentGetResponses];

export type GetUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Roles
         */
        roles?: Array<UserRole>;
        /**
         * Is Active
         */
        is_active?: number | null;
        /**
         * Is Online
         */
        is_online?: number | null;
        /**
         * Slugs
         */
        slugs?: Array<string>;
        /**
         * Events
         */
        events?: Array<string>;
    };
    url: '/api/users';
};

export type GetUsersApiUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersApiUsersGetError = GetUsersApiUsersGetErrors[keyof GetUsersApiUsersGetErrors];

export type GetUsersApiUsersGetResponses = {
    /**
     * Successful Response
     */
    200: UsersResponse;
};

export type GetUsersApiUsersGetResponse = GetUsersApiUsersGetResponses[keyof GetUsersApiUsersGetResponses];

export type GetGamesApiGamesHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Events
         */
        events?: Array<string>;
        /**
         * Players
         */
        players?: Array<string>;
        /**
         * Igdb Ids
         */
        igdb_ids?: Array<number>;
        /**
         * Titles
         */
        titles?: Array<string>;
        /**
         * Title Search
         */
        title_search?: string | null;
        /**
         * Completion Status
         */
        completion_status?: GameCompletionStatus | null;
        /**
         * Start Id
         */
        start_id?: number | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Exclude Ids
         */
        exclude_ids?: Array<number>;
    };
    url: '/api/games-history';
};

export type GetGamesApiGamesHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGamesApiGamesHistoryGetError = GetGamesApiGamesHistoryGetErrors[keyof GetGamesApiGamesHistoryGetErrors];

export type GetGamesApiGamesHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: GamesHistoryResponse;
};

export type GetGamesApiGamesHistoryGetResponse = GetGamesApiGamesHistoryGetResponses[keyof GetGamesApiGamesHistoryGetResponses];

export type StartGamesHistoryImportApiGamesHistoryImportStartGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/games-history/import/start';
};

export type StartGamesHistoryImportApiGamesHistoryImportStartGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGamesStatsEndpointApiGamesHistoryStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/games-history/stats';
};

export type GetGamesStatsEndpointApiGamesHistoryStatsGetResponses = {
    /**
     * Successful Response
     */
    200: GamesHistoryStatsResponse;
};

export type GetGamesStatsEndpointApiGamesHistoryStatsGetResponse = GetGamesStatsEndpointApiGamesHistoryStatsGetResponses[keyof GetGamesStatsEndpointApiGamesHistoryStatsGetResponses];

export type MakeDiceRollApiDiceRollsPostData = {
    body: DiceRollRequest;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/dice-rolls';
};

export type MakeDiceRollApiDiceRollsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MakeDiceRollApiDiceRollsPostError = MakeDiceRollApiDiceRollsPostErrors[keyof MakeDiceRollApiDiceRollsPostErrors];

export type MakeDiceRollApiDiceRollsPostResponses = {
    /**
     * Successful Response
     */
    200: DiceRollResponse;
};

export type MakeDiceRollApiDiceRollsPostResponse = MakeDiceRollApiDiceRollsPostResponses[keyof MakeDiceRollApiDiceRollsPostResponses];

export type GetRollByIdApiDiceRollsRollIdGetData = {
    body?: never;
    path: {
        /**
         * Roll Id
         */
        roll_id: number;
    };
    query?: never;
    url: '/api/dice-rolls/{roll_id}';
};

export type GetRollByIdApiDiceRollsRollIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRollByIdApiDiceRollsRollIdGetError = GetRollByIdApiDiceRollsRollIdGetErrors[keyof GetRollByIdApiDiceRollsRollIdGetErrors];

export type GetRollByIdApiDiceRollsRollIdGetResponses = {
    /**
     * Successful Response
     */
    200: DiceRollResponse;
};

export type GetRollByIdApiDiceRollsRollIdGetResponse = GetRollByIdApiDiceRollsRollIdGetResponses[keyof GetRollByIdApiDiceRollsRollIdGetResponses];

export type SearchIgdbGamesGetApiIgdbGamesSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/igdb/games/search';
};

export type SearchIgdbGamesGetApiIgdbGamesSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchIgdbGamesGetApiIgdbGamesSearchGetError = SearchIgdbGamesGetApiIgdbGamesSearchGetErrors[keyof SearchIgdbGamesGetApiIgdbGamesSearchGetErrors];

export type SearchIgdbGamesGetApiIgdbGamesSearchGetResponses = {
    /**
     * Successful Response
     */
    200: IgdbGamesListResponse;
};

export type SearchIgdbGamesGetApiIgdbGamesSearchGetResponse = SearchIgdbGamesGetApiIgdbGamesSearchGetResponses[keyof SearchIgdbGamesGetApiIgdbGamesSearchGetResponses];

export type StartIgdbUpdateApiIgdbUpdateStartGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/api/igdb/update/start';
};

export type StartIgdbUpdateApiIgdbUpdateStartGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartIgdbUpdateApiIgdbUpdateStartGetError = StartIgdbUpdateApiIgdbUpdateStartGetErrors[keyof StartIgdbUpdateApiIgdbUpdateStartGetErrors];

export type StartIgdbUpdateApiIgdbUpdateStartGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchGamesApiHltbSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search
         */
        search: string;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Exact
         */
        exact?: number;
    };
    url: '/api/hltb/search';
};

export type SearchGamesApiHltbSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchGamesApiHltbSearchGetError = SearchGamesApiHltbSearchGetErrors[keyof SearchGamesApiHltbSearchGetErrors];

export type SearchGamesApiHltbSearchGetResponses = {
    /**
     * Successful Response
     */
    200: HltbGamesListResponse;
};

export type SearchGamesApiHltbSearchGetResponse = SearchGamesApiHltbSearchGetResponses[keyof SearchGamesApiHltbSearchGetResponses];

export type StartHltbUpdateApiHltbUpdateStartGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Force
         */
        force?: boolean;
        /**
         * Only New
         */
        only_new?: boolean;
        /**
         * Only Missing
         */
        only_missing?: boolean;
    };
    url: '/api/hltb/update/start';
};

export type StartHltbUpdateApiHltbUpdateStartGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartHltbUpdateApiHltbUpdateStartGetError = StartHltbUpdateApiHltbUpdateStartGetErrors[keyof StartHltbUpdateApiHltbUpdateStartGetErrors];

export type StartHltbUpdateApiHltbUpdateStartGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RefreshStreamsApiStreamsRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/streams/refresh';
};

export type RefreshStreamsApiStreamsRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: StreamRefreshStats;
};

export type RefreshStreamsApiStreamsRefreshPostResponse = RefreshStreamsApiStreamsRefreshPostResponses[keyof RefreshStreamsApiStreamsRefreshPostResponses];

export type RefreshAvatarsApiStreamsRefreshAvatarsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/streams/refresh-avatars';
};

export type RefreshAvatarsApiStreamsRefreshAvatarsPostResponses = {
    /**
     * Successful Response
     */
    200: AvatarRefreshStats;
};

export type RefreshAvatarsApiStreamsRefreshAvatarsPostResponse = RefreshAvatarsApiStreamsRefreshAvatarsPostResponses[keyof RefreshAvatarsApiStreamsRefreshAvatarsPostResponses];

export type GetGameDurationApiStreamsGameDurationGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Slug
         */
        slug: string;
        /**
         * Game Name
         */
        game_name: string;
    };
    url: '/api/streams/game-duration';
};

export type GetGameDurationApiStreamsGameDurationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameDurationApiStreamsGameDurationGetError = GetGameDurationApiStreamsGameDurationGetErrors[keyof GetGameDurationApiStreamsGameDurationGetErrors];

export type GetGameDurationApiStreamsGameDurationGetResponses = {
    /**
     * Successful Response
     */
    200: GameDurationResponse;
};

export type GetGameDurationApiStreamsGameDurationGetResponse = GetGameDurationApiStreamsGameDurationGetResponses[keyof GetGameDurationApiStreamsGameDurationGetResponses];

export type CloseGameCategoriesApiStreamsCloseGameCategoriesPostData = {
    body: CloseGameCategoriesRequest;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/streams/close-game-categories';
};

export type CloseGameCategoriesApiStreamsCloseGameCategoriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloseGameCategoriesApiStreamsCloseGameCategoriesPostError = CloseGameCategoriesApiStreamsCloseGameCategoriesPostErrors[keyof CloseGameCategoriesApiStreamsCloseGameCategoriesPostErrors];

export type CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponses = {
    /**
     * Successful Response
     */
    200: CloseGameCategoriesResponse;
};

export type CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponse = CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponses[keyof CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponses];

export type GetNassalStreamsApiNassalStreamsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/nassal/streams';
};

export type GetNassalStreamsApiNassalStreamsGetResponses = {
    /**
     * Successful Response
     */
    200: NassalStreamsResponse;
};

export type GetNassalStreamsApiNassalStreamsGetResponse = GetNassalStreamsApiNassalStreamsGetResponses[keyof GetNassalStreamsApiNassalStreamsGetResponses];

export type GetEventsApiEventsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type GetEventsApiEventsGetResponses = {
    /**
     * Successful Response
     */
    200: EventsResponse;
};

export type GetEventsApiEventsGetResponse = GetEventsApiEventsGetResponses[keyof GetEventsApiEventsGetResponses];

export type SearchEmotesApiEmotesSearchPostData = {
    body: EmoteSearchRequest;
    path?: never;
    query?: never;
    url: '/api/emotes/search';
};

export type SearchEmotesApiEmotesSearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchEmotesApiEmotesSearchPostError = SearchEmotesApiEmotesSearchPostErrors[keyof SearchEmotesApiEmotesSearchPostErrors];

export type SearchEmotesApiEmotesSearchPostResponses = {
    /**
     * Successful Response
     */
    200: EmoteSearchResponse;
};

export type SearchEmotesApiEmotesSearchPostResponse = SearchEmotesApiEmotesSearchPostResponses[keyof SearchEmotesApiEmotesSearchPostResponses];

export type SendNotificationApiNotificationsSendPostData = {
    body: SendNotificationRequest;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/notifications/send';
};

export type SendNotificationApiNotificationsSendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendNotificationApiNotificationsSendPostError = SendNotificationApiNotificationsSendPostErrors[keyof SendNotificationApiNotificationsSendPostErrors];

export type SendNotificationApiNotificationsSendPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type NotifyPlayerMoveApiNotificationsPlayerMovePostData = {
    body: PlayerMoveNotificationRequest;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/notifications/player-move';
};

export type NotifyPlayerMoveApiNotificationsPlayerMovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotifyPlayerMoveApiNotificationsPlayerMovePostError = NotifyPlayerMoveApiNotificationsPlayerMovePostErrors[keyof NotifyPlayerMoveApiNotificationsPlayerMovePostErrors];

export type NotifyPlayerMoveApiNotificationsPlayerMovePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type NotifyPlayerOnlineApiNotificationsPlayerOnlinePostData = {
    body: PlayerOnlineNotificationRequest;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/notifications/player-online';
};

export type NotifyPlayerOnlineApiNotificationsPlayerOnlinePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotifyPlayerOnlineApiNotificationsPlayerOnlinePostError = NotifyPlayerOnlineApiNotificationsPlayerOnlinePostErrors[keyof NotifyPlayerOnlineApiNotificationsPlayerOnlinePostErrors];

export type NotifyPlayerOnlineApiNotificationsPlayerOnlinePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListOauthProvidersApiOauth2ProvidersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/oauth2/providers';
};

export type ListOauthProvidersApiOauth2ProvidersGetResponses = {
    /**
     * Successful Response
     */
    200: OAuthProvidersResponse;
};

export type ListOauthProvidersApiOauth2ProvidersGetResponse = ListOauthProvidersApiOauth2ProvidersGetResponses[keyof ListOauthProvidersApiOauth2ProvidersGetResponses];

export type AuthorizeOauthApiOauth2AuthorizePostData = {
    body: OAuthAuthorizeRequest;
    path?: never;
    query?: never;
    url: '/api/oauth2/authorize';
};

export type AuthorizeOauthApiOauth2AuthorizePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorizeOauthApiOauth2AuthorizePostError = AuthorizeOauthApiOauth2AuthorizePostErrors[keyof AuthorizeOauthApiOauth2AuthorizePostErrors];

export type AuthorizeOauthApiOauth2AuthorizePostResponses = {
    /**
     * Successful Response
     */
    200: OAuthAuthorizeResponse;
};

export type AuthorizeOauthApiOauth2AuthorizePostResponse = AuthorizeOauthApiOauth2AuthorizePostResponses[keyof AuthorizeOauthApiOauth2AuthorizePostResponses];

export type OauthCallbackGetApiOauth2CallbackGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
        /**
         * State
         */
        state: string;
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/oauth2/callback';
};

export type OauthCallbackGetApiOauth2CallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthCallbackGetApiOauth2CallbackGetError = OauthCallbackGetApiOauth2CallbackGetErrors[keyof OauthCallbackGetApiOauth2CallbackGetErrors];

export type OauthCallbackGetApiOauth2CallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OauthCallbackApiOauth2CallbackPostData = {
    body: OAuthCallbackRequest;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/oauth2/callback';
};

export type OauthCallbackApiOauth2CallbackPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthCallbackApiOauth2CallbackPostError = OauthCallbackApiOauth2CallbackPostErrors[keyof OauthCallbackApiOauth2CallbackPostErrors];

export type OauthCallbackApiOauth2CallbackPostResponses = {
    /**
     * Successful Response
     */
    200: OAuthCallbackResponse;
};

export type OauthCallbackApiOauth2CallbackPostResponse = OauthCallbackApiOauth2CallbackPostResponses[keyof OauthCallbackApiOauth2CallbackPostResponses];

export type ListUserIntegrationsApiOauth2IntegrationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/oauth2/integrations';
};

export type ListUserIntegrationsApiOauth2IntegrationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUserIntegrationsApiOauth2IntegrationsGetError = ListUserIntegrationsApiOauth2IntegrationsGetErrors[keyof ListUserIntegrationsApiOauth2IntegrationsGetErrors];

export type ListUserIntegrationsApiOauth2IntegrationsGetResponses = {
    /**
     * Successful Response
     */
    200: OAuthIntegrationsResponse;
};

export type ListUserIntegrationsApiOauth2IntegrationsGetResponse = ListUserIntegrationsApiOauth2IntegrationsGetResponses[keyof ListUserIntegrationsApiOauth2IntegrationsGetResponses];

export type DeleteIntegrationApiOauth2IntegrationsProviderNameDeleteData = {
    body?: never;
    path: {
        /**
         * Provider Name
         */
        provider_name: string;
    };
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/oauth2/integrations/{provider_name}';
};

export type DeleteIntegrationApiOauth2IntegrationsProviderNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteIntegrationApiOauth2IntegrationsProviderNameDeleteError = DeleteIntegrationApiOauth2IntegrationsProviderNameDeleteErrors[keyof DeleteIntegrationApiOauth2IntegrationsProviderNameDeleteErrors];

export type DeleteIntegrationApiOauth2IntegrationsProviderNameDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetIntegrationStatusApiOauth2IntegrationsProviderNameGetData = {
    body?: never;
    path: {
        /**
         * Provider Name
         */
        provider_name: string;
    };
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/oauth2/integrations/{provider_name}';
};

export type GetIntegrationStatusApiOauth2IntegrationsProviderNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetIntegrationStatusApiOauth2IntegrationsProviderNameGetError = GetIntegrationStatusApiOauth2IntegrationsProviderNameGetErrors[keyof GetIntegrationStatusApiOauth2IntegrationsProviderNameGetErrors];

export type GetIntegrationStatusApiOauth2IntegrationsProviderNameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RefreshIntegrationApiOauth2RefreshPostData = {
    body: OAuthRefreshRequest;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/oauth2/refresh';
};

export type RefreshIntegrationApiOauth2RefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshIntegrationApiOauth2RefreshPostError = RefreshIntegrationApiOauth2RefreshPostErrors[keyof RefreshIntegrationApiOauth2RefreshPostErrors];

export type RefreshIntegrationApiOauth2RefreshPostResponses = {
    /**
     * Successful Response
     */
    200: OAuthRefreshResponse;
};

export type RefreshIntegrationApiOauth2RefreshPostResponse = RefreshIntegrationApiOauth2RefreshPostResponses[keyof RefreshIntegrationApiOauth2RefreshPostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8094' | (string & {});
};
