// This file is auto-generated by @hey-api/openapi-ts

/**
 * DiceRollRequest
 */
export type DiceRollRequest = {
    dice: DiceType;
    /**
     * Used
     */
    used?: boolean;
    /**
     * Test Values
     */
    test_values?: Array<number>;
};

/**
 * DiceRollResponse
 */
export type DiceRollResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: number;
    /**
     * User Slug
     */
    user_slug: string;
    /**
     * Is Used
     */
    is_used: boolean;
    dice_type: DiceType;
    /**
     * Roll Values
     */
    roll_values: Array<number>;
    /**
     * Is Random Org Result
     */
    is_random_org_result: boolean;
    /**
     * Random Org Check Url
     */
    random_org_check_url: string | null;
    /**
     * Random Org Fail Reason
     */
    random_org_fail_reason: string | null;
};

/**
 * DiceType
 */
export type DiceType = '1d2' | '1d4' | '2d4' | '3d4' | '1d6' | '2d6' | '3d6' | '2d8';

/**
 * EmoteItem
 */
export type EmoteItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Owner Username
     */
    owner_username: string | null;
    /**
     * Listed
     */
    listed: boolean;
    /**
     * Cdn Url
     */
    cdn_url: string;
};

/**
 * EmoteSearchRequest
 */
export type EmoteSearchRequest = {
    /**
     * Search Term
     */
    search_term?: string;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Page
     */
    page?: number;
};

/**
 * EmoteSearchResponse
 */
export type EmoteSearchResponse = {
    /**
     * Emotes
     */
    emotes: Array<EmoteItem>;
};

/**
 * EventItem
 */
export type EventItem = {
    /**
     * Organizer Id
     */
    organizer_id: number;
    /**
     * Slug
     */
    slug: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Start Timestamp
     */
    start_timestamp: number;
    /**
     * End Timestamp
     */
    end_timestamp: number | null;
    /**
     * Participants
     */
    participants: Array<EventParticipantItem>;
    /**
     * Link
     */
    link: string | null;
    /**
     * Banner Url
     */
    banner_url: string;
    /**
     * Logo Url
     */
    logo_url: string;
    /**
     * Developer Slug
     */
    developer_slug: string;
};

/**
 * EventName
 */
export type EventName = 'aukus1' | 'aukus2' | 'aukus3' | 'aukus4' | 'igropolius' | 'MGE';

/**
 * EventParticipantItem
 */
export type EventParticipantItem = {
    /**
     * User Slug
     */
    user_slug: string;
    /**
     * Placement
     */
    placement: number | null;
};

/**
 * EventsResponse
 */
export type EventsResponse = {
    /**
     * Events
     */
    events: Array<EventItem>;
};

/**
 * GameCompletionStatus
 */
export type GameCompletionStatus = 'completed' | 'reroll' | 'drop';

/**
 * GameHistoryItem
 */
export type GameHistoryItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Player Name
     */
    player_name: string;
    event_name: EventName;
    /**
     * Game Title
     */
    game_title: string;
    /**
     * Game Cover
     */
    game_cover: string;
    /**
     * Game Link
     */
    game_link: string;
    completion_status: GameCompletionStatus;
    /**
     * Timestamp
     */
    timestamp: number | null;
    /**
     * Review
     */
    review: string;
    /**
     * Rating
     */
    rating: string;
    /**
     * Game Time
     */
    game_time: number;
    /**
     * Difficulty
     */
    difficulty: string;
    /**
     * Game Id
     */
    game_id: number | null;
};

/**
 * GamesHistoryResponse
 */
export type GamesHistoryResponse = {
    /**
     * Games
     */
    games: Array<GameHistoryItem>;
    /**
     * Next Id
     */
    next_id: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IgdbGameSummary
 */
export type IgdbGameSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Cover
     */
    cover?: string | null;
    /**
     * Release Year
     */
    release_year?: number | null;
};

/**
 * IgdbGamesListResponse
 */
export type IgdbGamesListResponse = {
    /**
     * Games
     */
    games: Array<IgdbGameSummary>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Token
     */
    token: string;
};

/**
 * UserItem
 */
export type UserItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Slug
     */
    slug: string;
    /**
     * Username
     */
    username: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Roles
     */
    roles: Array<UserRole>;
    /**
     * Moder For
     */
    moder_for: Array<string>;
    /**
     * Is Active
     */
    is_active: number;
    /**
     * Is Online
     */
    is_online: number;
    /**
     * Current Game
     */
    current_game: string | null;
    /**
     * Current Game Cover
     */
    current_game_cover: string | null;
    /**
     * Current Game Updated At
     */
    current_game_updated_at: number | null;
    /**
     * Current Game Duration
     */
    current_game_duration: number;
    /**
     * Online Count
     */
    online_count: number;
    /**
     * Main Platform
     */
    main_platform: string | null;
    /**
     * Twitch Stream Link
     */
    twitch_stream_link: string | null;
    /**
     * Vk Stream Link
     */
    vk_stream_link: string | null;
    /**
     * Kick Stream Link
     */
    kick_stream_link: string | null;
    /**
     * Telegram Link
     */
    telegram_link: string | null;
    /**
     * Donation Link
     */
    donation_link: string | null;
    /**
     * Avatar Link
     */
    avatar_link: string | null;
    /**
     * Color
     */
    color: string | null;
};

/**
 * UserRole
 */
export type UserRole = 'streamer' | 'admin' | 'rules.edit';

/**
 * UsersResponse
 */
export type UsersResponse = {
    /**
     * Users
     */
    users: Array<UserItem>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginApiLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LoginApiLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiLoginPostError = LoginApiLoginPostErrors[keyof LoginApiLoginPostErrors];

export type LoginApiLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiLoginPostResponse = LoginApiLoginPostResponses[keyof LoginApiLoginPostResponses];

export type LogoutApiLogoutPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/logout';
};

export type LogoutApiLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiLogoutPostError = LogoutApiLogoutPostErrors[keyof LogoutApiLogoutPostErrors];

export type LogoutApiLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FetchCurrentUserApiUsersCurrentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/users/current';
};

export type FetchCurrentUserApiUsersCurrentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FetchCurrentUserApiUsersCurrentGetError = FetchCurrentUserApiUsersCurrentGetErrors[keyof FetchCurrentUserApiUsersCurrentGetErrors];

export type FetchCurrentUserApiUsersCurrentGetResponses = {
    /**
     * Successful Response
     */
    200: UserItem;
};

export type FetchCurrentUserApiUsersCurrentGetResponse = FetchCurrentUserApiUsersCurrentGetResponses[keyof FetchCurrentUserApiUsersCurrentGetResponses];

export type GetUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Roles
         */
        roles?: Array<UserRole>;
        /**
         * Is Active
         */
        is_active?: number | null;
        /**
         * Is Online
         */
        is_online?: number | null;
        /**
         * Slugs
         */
        slugs?: Array<string>;
        /**
         * Events
         */
        events?: Array<EventName>;
    };
    url: '/api/users';
};

export type GetUsersApiUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersApiUsersGetError = GetUsersApiUsersGetErrors[keyof GetUsersApiUsersGetErrors];

export type GetUsersApiUsersGetResponses = {
    /**
     * Successful Response
     */
    200: UsersResponse;
};

export type GetUsersApiUsersGetResponse = GetUsersApiUsersGetResponses[keyof GetUsersApiUsersGetResponses];

export type GetGamesApiGamesHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Events
         */
        events?: Array<EventName>;
        /**
         * Players
         */
        players?: Array<string>;
        /**
         * Titles
         */
        titles?: Array<string>;
        /**
         * Title Search
         */
        title_search?: string | null;
        /**
         * Completion Status
         */
        completion_status?: GameCompletionStatus | null;
        /**
         * Start Id
         */
        start_id?: number | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Exclude Ids
         */
        exclude_ids?: Array<number>;
    };
    url: '/api/games-history';
};

export type GetGamesApiGamesHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGamesApiGamesHistoryGetError = GetGamesApiGamesHistoryGetErrors[keyof GetGamesApiGamesHistoryGetErrors];

export type GetGamesApiGamesHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: GamesHistoryResponse;
};

export type GetGamesApiGamesHistoryGetResponse = GetGamesApiGamesHistoryGetResponses[keyof GetGamesApiGamesHistoryGetResponses];

export type MakeDiceRollApiDiceRollsPostData = {
    body: DiceRollRequest;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/dice-rolls';
};

export type MakeDiceRollApiDiceRollsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MakeDiceRollApiDiceRollsPostError = MakeDiceRollApiDiceRollsPostErrors[keyof MakeDiceRollApiDiceRollsPostErrors];

export type MakeDiceRollApiDiceRollsPostResponses = {
    /**
     * Successful Response
     */
    200: DiceRollResponse;
};

export type MakeDiceRollApiDiceRollsPostResponse = MakeDiceRollApiDiceRollsPostResponses[keyof MakeDiceRollApiDiceRollsPostResponses];

export type GetRollByIdApiDiceRollsRollIdGetData = {
    body?: never;
    path: {
        /**
         * Roll Id
         */
        roll_id: number;
    };
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/dice-rolls/{roll_id}';
};

export type GetRollByIdApiDiceRollsRollIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRollByIdApiDiceRollsRollIdGetError = GetRollByIdApiDiceRollsRollIdGetErrors[keyof GetRollByIdApiDiceRollsRollIdGetErrors];

export type GetRollByIdApiDiceRollsRollIdGetResponses = {
    /**
     * Successful Response
     */
    200: DiceRollResponse;
};

export type GetRollByIdApiDiceRollsRollIdGetResponse = GetRollByIdApiDiceRollsRollIdGetResponses[keyof GetRollByIdApiDiceRollsRollIdGetResponses];

export type SearchIgdbGamesGetApiIgdbGamesSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * Limit
         */
        limit?: number;
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/igdb/games/search';
};

export type SearchIgdbGamesGetApiIgdbGamesSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchIgdbGamesGetApiIgdbGamesSearchGetError = SearchIgdbGamesGetApiIgdbGamesSearchGetErrors[keyof SearchIgdbGamesGetApiIgdbGamesSearchGetErrors];

export type SearchIgdbGamesGetApiIgdbGamesSearchGetResponses = {
    /**
     * Successful Response
     */
    200: IgdbGamesListResponse;
};

export type SearchIgdbGamesGetApiIgdbGamesSearchGetResponse = SearchIgdbGamesGetApiIgdbGamesSearchGetResponses[keyof SearchIgdbGamesGetApiIgdbGamesSearchGetResponses];

export type StartIgdbUpdateApiIgdbUpdateStartGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/api/igdb/update/start';
};

export type StartIgdbUpdateApiIgdbUpdateStartGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartIgdbUpdateApiIgdbUpdateStartGetError = StartIgdbUpdateApiIgdbUpdateStartGetErrors[keyof StartIgdbUpdateApiIgdbUpdateStartGetErrors];

export type StartIgdbUpdateApiIgdbUpdateStartGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RefreshStreamsApiStreamsRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/streams/refresh';
};

export type RefreshStreamsApiStreamsRefreshPostResponses = {
    /**
     * Response Refresh Streams Api Streams Refresh Post
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RefreshStreamsApiStreamsRefreshPostResponse = RefreshStreamsApiStreamsRefreshPostResponses[keyof RefreshStreamsApiStreamsRefreshPostResponses];

export type RefreshAvatarsApiStreamsRefreshAvatarsPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/streams/refresh-avatars';
};

export type RefreshAvatarsApiStreamsRefreshAvatarsPostResponses = {
    /**
     * Response Refresh Avatars Api Streams Refresh Avatars Post
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RefreshAvatarsApiStreamsRefreshAvatarsPostResponse = RefreshAvatarsApiStreamsRefreshAvatarsPostResponses[keyof RefreshAvatarsApiStreamsRefreshAvatarsPostResponses];

export type GetGameDurationApiStreamsGameDurationGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Slug
         */
        slug: string;
        /**
         * Game Name
         */
        game_name: string;
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/streams/game-duration';
};

export type GetGameDurationApiStreamsGameDurationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameDurationApiStreamsGameDurationGetError = GetGameDurationApiStreamsGameDurationGetErrors[keyof GetGameDurationApiStreamsGameDurationGetErrors];

export type GetGameDurationApiStreamsGameDurationGetResponses = {
    /**
     * Response Get Game Duration Api Streams Game Duration Get
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetGameDurationApiStreamsGameDurationGetResponse = GetGameDurationApiStreamsGameDurationGetResponses[keyof GetGameDurationApiStreamsGameDurationGetResponses];

export type CloseGameCategoriesApiStreamsCloseGameCategoriesPostData = {
    /**
     * Request
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/streams/close-game-categories';
};

export type CloseGameCategoriesApiStreamsCloseGameCategoriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloseGameCategoriesApiStreamsCloseGameCategoriesPostError = CloseGameCategoriesApiStreamsCloseGameCategoriesPostErrors[keyof CloseGameCategoriesApiStreamsCloseGameCategoriesPostErrors];

export type CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponses = {
    /**
     * Response Close Game Categories Api Streams Close Game Categories Post
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponse = CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponses[keyof CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponses];

export type GetEventsApiEventsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type GetEventsApiEventsGetResponses = {
    /**
     * Successful Response
     */
    200: EventsResponse;
};

export type GetEventsApiEventsGetResponse = GetEventsApiEventsGetResponses[keyof GetEventsApiEventsGetResponses];

export type SearchEmotesApiEmotesSearchPostData = {
    body: EmoteSearchRequest;
    path?: never;
    query?: never;
    url: '/api/emotes/search';
};

export type SearchEmotesApiEmotesSearchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchEmotesApiEmotesSearchPostError = SearchEmotesApiEmotesSearchPostErrors[keyof SearchEmotesApiEmotesSearchPostErrors];

export type SearchEmotesApiEmotesSearchPostResponses = {
    /**
     * Successful Response
     */
    200: EmoteSearchResponse;
};

export type SearchEmotesApiEmotesSearchPostResponse = SearchEmotesApiEmotesSearchPostResponses[keyof SearchEmotesApiEmotesSearchPostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8300' | (string & {});
};
