// This file is auto-generated by @hey-api/openapi-ts

/**
 * DiceRollRequest
 */
export type DiceRollRequest = {
    dice: DiceType;
    /**
     * Used
     */
    used?: boolean;
    /**
     * Test Values
     */
    test_values?: Array<number>;
};

/**
 * DiceRollResponse
 */
export type DiceRollResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: number;
    /**
     * User Slug
     */
    user_slug: string;
    /**
     * Is Used
     */
    is_used: boolean;
    dice_type: DiceType;
    /**
     * Roll Values
     */
    roll_values: Array<number>;
    /**
     * Is Random Org Result
     */
    is_random_org_result: boolean;
    /**
     * Random Org Check Url
     */
    random_org_check_url: string | null;
    /**
     * Random Org Fail Reason
     */
    random_org_fail_reason: string | null;
};

/**
 * DiceType
 */
export type DiceType = '1d4' | '2d4' | '1d6' | '2d6' | '3d6' | '2d8';

/**
 * EventName
 */
export type EventName = 'aukus1' | 'aukus2' | 'aukus3' | 'aukus4' | 'igropolius';

/**
 * GameCompletionStatus
 */
export type GameCompletionStatus = 'completed' | 'reroll' | 'drop';

/**
 * GameHistoryItem
 */
export type GameHistoryItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Player Name
     */
    player_name: string;
    /**
     * Event Name
     */
    event_name: string;
    /**
     * Game Title
     */
    game_title: string;
    /**
     * Game Cover
     */
    game_cover: string;
    /**
     * Game Link
     */
    game_link: string;
    completion_status: GameCompletionStatus;
    /**
     * Timestamp
     */
    timestamp: number;
    /**
     * Review
     */
    review: string;
    /**
     * Rating
     */
    rating: string;
    /**
     * Game Time
     */
    game_time: number;
    /**
     * Difficulty
     */
    difficulty: string;
    /**
     * Game Id
     */
    game_id: number;
};

/**
 * GamesHistoryResponse
 */
export type GamesHistoryResponse = {
    /**
     * Games
     */
    games: Array<GameHistoryItem>;
    /**
     * Count
     */
    count: number;
    /**
     * Last Ts
     */
    last_ts: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IgdbGameSummary
 */
export type IgdbGameSummary = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Cover
     */
    cover?: string | null;
    /**
     * Release Year
     */
    release_year?: number | null;
};

/**
 * IgdbGamesListResponse
 */
export type IgdbGamesListResponse = {
    /**
     * Games
     */
    games: Array<IgdbGameSummary>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Token
     */
    token: string;
};

/**
 * UserItem
 */
export type UserItem = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Username
     */
    username: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Roles
     */
    roles: Array<UserRole>;
    /**
     * Moder For
     */
    moder_for: Array<string>;
    /**
     * Is Active
     */
    is_active: number;
    /**
     * Is Online
     */
    is_online: number;
    /**
     * Current Game
     */
    current_game: string | null;
    /**
     * Current Game Cover
     */
    current_game_cover: string | null;
    /**
     * Current Game Updated At
     */
    current_game_updated_at: number | null;
    /**
     * Current Game Duration
     */
    current_game_duration: number;
    /**
     * Online Count
     */
    online_count: number;
    /**
     * Main Platform
     */
    main_platform: string | null;
    /**
     * Twitch Stream Link
     */
    twitch_stream_link: string | null;
    /**
     * Vk Stream Link
     */
    vk_stream_link: string | null;
    /**
     * Kick Stream Link
     */
    kick_stream_link: string | null;
    /**
     * Telegram Link
     */
    telegram_link: string | null;
    /**
     * Donation Link
     */
    donation_link: string | null;
    /**
     * Avatar Link
     */
    avatar_link: string | null;
    /**
     * Color
     */
    color: string | null;
};

/**
 * UserRole
 */
export type UserRole = 'streamer' | 'admin' | 'rules.edit';

/**
 * UsersResponse
 */
export type UsersResponse = {
    /**
     * Users
     */
    users: Array<UserItem>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginApiLoginPostData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LoginApiLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiLoginPostError = LoginApiLoginPostErrors[keyof LoginApiLoginPostErrors];

export type LoginApiLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiLoginPostResponse = LoginApiLoginPostResponses[keyof LoginApiLoginPostResponses];

export type LogoutApiLogoutPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/logout';
};

export type LogoutApiLogoutPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutApiLogoutPostError = LogoutApiLogoutPostErrors[keyof LogoutApiLogoutPostErrors];

export type LogoutApiLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type FetchCurrentUserApiUsersCurrentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/users/current';
};

export type FetchCurrentUserApiUsersCurrentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FetchCurrentUserApiUsersCurrentGetError = FetchCurrentUserApiUsersCurrentGetErrors[keyof FetchCurrentUserApiUsersCurrentGetErrors];

export type FetchCurrentUserApiUsersCurrentGetResponses = {
    /**
     * Successful Response
     */
    200: UserItem;
};

export type FetchCurrentUserApiUsersCurrentGetResponse = FetchCurrentUserApiUsersCurrentGetResponses[keyof FetchCurrentUserApiUsersCurrentGetResponses];

export type GetUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Roles
         */
        roles?: Array<UserRole>;
        /**
         * Is Active
         */
        is_active?: number | null;
        /**
         * Is Online
         */
        is_online?: number | null;
        /**
         * Slugs
         */
        slugs?: Array<string>;
        /**
         * Events
         */
        events?: Array<EventName>;
    };
    url: '/api/users';
};

export type GetUsersApiUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersApiUsersGetError = GetUsersApiUsersGetErrors[keyof GetUsersApiUsersGetErrors];

export type GetUsersApiUsersGetResponses = {
    /**
     * Successful Response
     */
    200: UsersResponse;
};

export type GetUsersApiUsersGetResponse = GetUsersApiUsersGetResponses[keyof GetUsersApiUsersGetResponses];

export type GetGamesApiGamesHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Events
         */
        events?: Array<EventName>;
        /**
         * Player Name
         */
        player_name?: string | null;
        /**
         * Title Search
         */
        title_search?: string | null;
        /**
         * Completion Status
         */
        completion_status?: GameCompletionStatus | null;
        /**
         * Start Ts
         */
        start_ts?: number | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/games-history';
};

export type GetGamesApiGamesHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGamesApiGamesHistoryGetError = GetGamesApiGamesHistoryGetErrors[keyof GetGamesApiGamesHistoryGetErrors];

export type GetGamesApiGamesHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: GamesHistoryResponse;
};

export type GetGamesApiGamesHistoryGetResponse = GetGamesApiGamesHistoryGetResponses[keyof GetGamesApiGamesHistoryGetResponses];

export type MakeDiceRollApiDiceRollsPostData = {
    body: DiceRollRequest;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/dice-rolls';
};

export type MakeDiceRollApiDiceRollsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MakeDiceRollApiDiceRollsPostError = MakeDiceRollApiDiceRollsPostErrors[keyof MakeDiceRollApiDiceRollsPostErrors];

export type MakeDiceRollApiDiceRollsPostResponses = {
    /**
     * Successful Response
     */
    200: DiceRollResponse;
};

export type MakeDiceRollApiDiceRollsPostResponse = MakeDiceRollApiDiceRollsPostResponses[keyof MakeDiceRollApiDiceRollsPostResponses];

export type GetRollByIdApiDiceRollsRollIdGetData = {
    body?: never;
    path: {
        /**
         * Roll Id
         */
        roll_id: number;
    };
    query?: never;
    url: '/api/dice-rolls/{roll_id}';
};

export type GetRollByIdApiDiceRollsRollIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetRollByIdApiDiceRollsRollIdGetError = GetRollByIdApiDiceRollsRollIdGetErrors[keyof GetRollByIdApiDiceRollsRollIdGetErrors];

export type GetRollByIdApiDiceRollsRollIdGetResponses = {
    /**
     * Successful Response
     */
    200: DiceRollResponse;
};

export type GetRollByIdApiDiceRollsRollIdGetResponse = GetRollByIdApiDiceRollsRollIdGetResponses[keyof GetRollByIdApiDiceRollsRollIdGetResponses];

export type SearchIgdbGamesGetApiIgdbGamesSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * Limit
         */
        limit?: number;
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/igdb/games/search';
};

export type SearchIgdbGamesGetApiIgdbGamesSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchIgdbGamesGetApiIgdbGamesSearchGetError = SearchIgdbGamesGetApiIgdbGamesSearchGetErrors[keyof SearchIgdbGamesGetApiIgdbGamesSearchGetErrors];

export type SearchIgdbGamesGetApiIgdbGamesSearchGetResponses = {
    /**
     * Successful Response
     */
    200: IgdbGamesListResponse;
};

export type SearchIgdbGamesGetApiIgdbGamesSearchGetResponse = SearchIgdbGamesGetApiIgdbGamesSearchGetResponses[keyof SearchIgdbGamesGetApiIgdbGamesSearchGetResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8300' | (string & {});
};
