// This file is auto-generated by @hey-api/openapi-ts

import { type Options, testExceptionApiTestExceptionGet, loginApiLoginPost, logoutApiLogoutPost, fetchCurrentUserApiUsersCurrentGet, getUsersApiUsersGet, getGamesApiGamesHistoryGet, startGamesHistoryImportApiGamesHistoryImportStartGet, getGamesStatsEndpointApiGamesHistoryStatsGet, makeDiceRollApiDiceRollsPost, getRollByIdApiDiceRollsRollIdGet, searchIgdbGamesGetApiIgdbGamesSearchGet, startIgdbUpdateApiIgdbUpdateStartGet, searchGamesApiHltbSearchGet, startHltbUpdateApiHltbUpdateStartGet, refreshStreamsApiStreamsRefreshPost, refreshAvatarsApiStreamsRefreshAvatarsPost, getGameDurationApiStreamsGameDurationGet, closeGameCategoriesApiStreamsCloseGameCategoriesPost, getNassalStreamsApiNassalStreamsGet, getEventsApiEventsGet, searchEmotesApiEmotesSearchPost, sendNotificationApiNotificationsSendPost, notifyPlayerMoveApiNotificationsPlayerMovePost, notifyPlayerOnlineApiNotificationsPlayerOnlinePost } from '../sdk.gen';
import { queryOptions, type MutationOptions, type DefaultError } from '@tanstack/svelte-query';
import type { TestExceptionApiTestExceptionGetData, LoginApiLoginPostData, LoginApiLoginPostError, LoginApiLoginPostResponse, LogoutApiLogoutPostData, LogoutApiLogoutPostError, FetchCurrentUserApiUsersCurrentGetData, GetUsersApiUsersGetData, GetGamesApiGamesHistoryGetData, StartGamesHistoryImportApiGamesHistoryImportStartGetData, GetGamesStatsEndpointApiGamesHistoryStatsGetData, MakeDiceRollApiDiceRollsPostData, MakeDiceRollApiDiceRollsPostError, MakeDiceRollApiDiceRollsPostResponse, GetRollByIdApiDiceRollsRollIdGetData, SearchIgdbGamesGetApiIgdbGamesSearchGetData, StartIgdbUpdateApiIgdbUpdateStartGetData, SearchGamesApiHltbSearchGetData, StartHltbUpdateApiHltbUpdateStartGetData, RefreshStreamsApiStreamsRefreshPostData, RefreshStreamsApiStreamsRefreshPostResponse, RefreshAvatarsApiStreamsRefreshAvatarsPostData, RefreshAvatarsApiStreamsRefreshAvatarsPostResponse, GetGameDurationApiStreamsGameDurationGetData, CloseGameCategoriesApiStreamsCloseGameCategoriesPostData, CloseGameCategoriesApiStreamsCloseGameCategoriesPostError, CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponse, GetNassalStreamsApiNassalStreamsGetData, GetEventsApiEventsGetData, SearchEmotesApiEmotesSearchPostData, SearchEmotesApiEmotesSearchPostError, SearchEmotesApiEmotesSearchPostResponse, SendNotificationApiNotificationsSendPostData, SendNotificationApiNotificationsSendPostError, NotifyPlayerMoveApiNotificationsPlayerMovePostData, NotifyPlayerMoveApiNotificationsPlayerMovePostError, NotifyPlayerOnlineApiNotificationsPlayerOnlinePostData, NotifyPlayerOnlineApiNotificationsPlayerOnlinePostError } from '../types.gen';
import { client } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const testExceptionApiTestExceptionGetQueryKey = (options?: Options<TestExceptionApiTestExceptionGetData>) => createQueryKey('testExceptionApiTestExceptionGet', options);

/**
 * Test Exception
 * Test endpoint to simulate an exception
 */
export const testExceptionApiTestExceptionGetOptions = (options?: Options<TestExceptionApiTestExceptionGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await testExceptionApiTestExceptionGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: testExceptionApiTestExceptionGetQueryKey(options)
    });
};

/**
 * Login
 */
export const loginApiLoginPostMutation = (options?: Partial<Options<LoginApiLoginPostData>>): MutationOptions<LoginApiLoginPostResponse, LoginApiLoginPostError, Options<LoginApiLoginPostData>> => {
    const mutationOptions: MutationOptions<LoginApiLoginPostResponse, LoginApiLoginPostError, Options<LoginApiLoginPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginApiLoginPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const logoutApiLogoutPostMutation = (options?: Partial<Options<LogoutApiLogoutPostData>>): MutationOptions<unknown, LogoutApiLogoutPostError, Options<LogoutApiLogoutPostData>> => {
    const mutationOptions: MutationOptions<unknown, LogoutApiLogoutPostError, Options<LogoutApiLogoutPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutApiLogoutPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const fetchCurrentUserApiUsersCurrentGetQueryKey = (options?: Options<FetchCurrentUserApiUsersCurrentGetData>) => createQueryKey('fetchCurrentUserApiUsersCurrentGet', options);

/**
 * Fetch Current User
 */
export const fetchCurrentUserApiUsersCurrentGetOptions = (options?: Options<FetchCurrentUserApiUsersCurrentGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await fetchCurrentUserApiUsersCurrentGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: fetchCurrentUserApiUsersCurrentGetQueryKey(options)
    });
};

export const getUsersApiUsersGetQueryKey = (options?: Options<GetUsersApiUsersGetData>) => createQueryKey('getUsersApiUsersGet', options);

/**
 * Get Users
 */
export const getUsersApiUsersGetOptions = (options?: Options<GetUsersApiUsersGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUsersApiUsersGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUsersApiUsersGetQueryKey(options)
    });
};

export const getGamesApiGamesHistoryGetQueryKey = (options?: Options<GetGamesApiGamesHistoryGetData>) => createQueryKey('getGamesApiGamesHistoryGet', options);

/**
 * Get Games
 */
export const getGamesApiGamesHistoryGetOptions = (options?: Options<GetGamesApiGamesHistoryGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getGamesApiGamesHistoryGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getGamesApiGamesHistoryGetQueryKey(options)
    });
};

export const startGamesHistoryImportApiGamesHistoryImportStartGetQueryKey = (options?: Options<StartGamesHistoryImportApiGamesHistoryImportStartGetData>) => createQueryKey('startGamesHistoryImportApiGamesHistoryImportStartGet', options);

/**
 * Start Games History Import
 */
export const startGamesHistoryImportApiGamesHistoryImportStartGetOptions = (options?: Options<StartGamesHistoryImportApiGamesHistoryImportStartGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await startGamesHistoryImportApiGamesHistoryImportStartGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: startGamesHistoryImportApiGamesHistoryImportStartGetQueryKey(options)
    });
};

export const getGamesStatsEndpointApiGamesHistoryStatsGetQueryKey = (options?: Options<GetGamesStatsEndpointApiGamesHistoryStatsGetData>) => createQueryKey('getGamesStatsEndpointApiGamesHistoryStatsGet', options);

/**
 * Get Games Stats Endpoint
 */
export const getGamesStatsEndpointApiGamesHistoryStatsGetOptions = (options?: Options<GetGamesStatsEndpointApiGamesHistoryStatsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getGamesStatsEndpointApiGamesHistoryStatsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getGamesStatsEndpointApiGamesHistoryStatsGetQueryKey(options)
    });
};

/**
 * Make Dice Roll
 */
export const makeDiceRollApiDiceRollsPostMutation = (options?: Partial<Options<MakeDiceRollApiDiceRollsPostData>>): MutationOptions<MakeDiceRollApiDiceRollsPostResponse, MakeDiceRollApiDiceRollsPostError, Options<MakeDiceRollApiDiceRollsPostData>> => {
    const mutationOptions: MutationOptions<MakeDiceRollApiDiceRollsPostResponse, MakeDiceRollApiDiceRollsPostError, Options<MakeDiceRollApiDiceRollsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await makeDiceRollApiDiceRollsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRollByIdApiDiceRollsRollIdGetQueryKey = (options: Options<GetRollByIdApiDiceRollsRollIdGetData>) => createQueryKey('getRollByIdApiDiceRollsRollIdGet', options);

/**
 * Get Roll By Id
 */
export const getRollByIdApiDiceRollsRollIdGetOptions = (options: Options<GetRollByIdApiDiceRollsRollIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRollByIdApiDiceRollsRollIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRollByIdApiDiceRollsRollIdGetQueryKey(options)
    });
};

export const searchIgdbGamesGetApiIgdbGamesSearchGetQueryKey = (options: Options<SearchIgdbGamesGetApiIgdbGamesSearchGetData>) => createQueryKey('searchIgdbGamesGetApiIgdbGamesSearchGet', options);

/**
 * Search Igdb Games Get
 */
export const searchIgdbGamesGetApiIgdbGamesSearchGetOptions = (options: Options<SearchIgdbGamesGetApiIgdbGamesSearchGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await searchIgdbGamesGetApiIgdbGamesSearchGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: searchIgdbGamesGetApiIgdbGamesSearchGetQueryKey(options)
    });
};

export const startIgdbUpdateApiIgdbUpdateStartGetQueryKey = (options?: Options<StartIgdbUpdateApiIgdbUpdateStartGetData>) => createQueryKey('startIgdbUpdateApiIgdbUpdateStartGet', options);

/**
 * Start Igdb Update
 */
export const startIgdbUpdateApiIgdbUpdateStartGetOptions = (options?: Options<StartIgdbUpdateApiIgdbUpdateStartGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await startIgdbUpdateApiIgdbUpdateStartGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: startIgdbUpdateApiIgdbUpdateStartGetQueryKey(options)
    });
};

export const searchGamesApiHltbSearchGetQueryKey = (options: Options<SearchGamesApiHltbSearchGetData>) => createQueryKey('searchGamesApiHltbSearchGet', options);

/**
 * Search Games
 */
export const searchGamesApiHltbSearchGetOptions = (options: Options<SearchGamesApiHltbSearchGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await searchGamesApiHltbSearchGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: searchGamesApiHltbSearchGetQueryKey(options)
    });
};

export const startHltbUpdateApiHltbUpdateStartGetQueryKey = (options?: Options<StartHltbUpdateApiHltbUpdateStartGetData>) => createQueryKey('startHltbUpdateApiHltbUpdateStartGet', options);

/**
 * Start Hltb Update
 */
export const startHltbUpdateApiHltbUpdateStartGetOptions = (options?: Options<StartHltbUpdateApiHltbUpdateStartGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await startHltbUpdateApiHltbUpdateStartGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: startHltbUpdateApiHltbUpdateStartGetQueryKey(options)
    });
};

/**
 * Refresh Streams
 * Refresh stream statuses for all active streamers.
 *
 * Returns statistics about the refresh operation:
 * - total_players: Total number of active players checked
 * - updated_players: Number of players whose status changed
 * - online_players: Number of players currently online
 * - errors: List of error messages if any occurred
 */
export const refreshStreamsApiStreamsRefreshPostMutation = (options?: Partial<Options<RefreshStreamsApiStreamsRefreshPostData>>): MutationOptions<RefreshStreamsApiStreamsRefreshPostResponse, DefaultError, Options<RefreshStreamsApiStreamsRefreshPostData>> => {
    const mutationOptions: MutationOptions<RefreshStreamsApiStreamsRefreshPostResponse, DefaultError, Options<RefreshStreamsApiStreamsRefreshPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refreshStreamsApiStreamsRefreshPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Refresh Avatars
 * Refresh avatars for all users with main platform and stream link.
 *
 * Returns statistics about the refresh operation:
 * - total_users: Total number of users checked
 * - updated_users: Number of users whose avatar was updated
 * - errors: List of error messages if any occurred
 */
export const refreshAvatarsApiStreamsRefreshAvatarsPostMutation = (options?: Partial<Options<RefreshAvatarsApiStreamsRefreshAvatarsPostData>>): MutationOptions<RefreshAvatarsApiStreamsRefreshAvatarsPostResponse, DefaultError, Options<RefreshAvatarsApiStreamsRefreshAvatarsPostData>> => {
    const mutationOptions: MutationOptions<RefreshAvatarsApiStreamsRefreshAvatarsPostResponse, DefaultError, Options<RefreshAvatarsApiStreamsRefreshAvatarsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refreshAvatarsApiStreamsRefreshAvatarsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getGameDurationApiStreamsGameDurationGetQueryKey = (options: Options<GetGameDurationApiStreamsGameDurationGetData>) => createQueryKey('getGameDurationApiStreamsGameDurationGet', options);

/**
 * Get Game Duration
 * Get total duration of all open categories for a specific game within active event.
 *
 * Used by aukus-backend when creating a player move to calculate item_duration.
 *
 * Returns:
 * - duration: Total seconds of all open category sessions
 * - sessions_count: Number of open sessions
 * - event_slug: Slug of the active event (if any)
 */
export const getGameDurationApiStreamsGameDurationGetOptions = (options: Options<GetGameDurationApiStreamsGameDurationGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getGameDurationApiStreamsGameDurationGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getGameDurationApiStreamsGameDurationGetQueryKey(options)
    });
};

/**
 * Close Game Categories
 * Close all open categories for a specific game within active event.
 *
 * Called by aukus-backend after creating a player move to mark the game session as complete.
 * This ensures that if the player starts the same game again, the timer resets.
 *
 * Request body:
 * - slug: User slug
 * - game_name: Name of the game to close categories for
 *
 * Returns:
 * - status: Operation status
 * - closed: Number of categories closed
 * - game_name: Name of the game
 * - event_slug: Slug of the active event (if any)
 */
export const closeGameCategoriesApiStreamsCloseGameCategoriesPostMutation = (options?: Partial<Options<CloseGameCategoriesApiStreamsCloseGameCategoriesPostData>>): MutationOptions<CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponse, CloseGameCategoriesApiStreamsCloseGameCategoriesPostError, Options<CloseGameCategoriesApiStreamsCloseGameCategoriesPostData>> => {
    const mutationOptions: MutationOptions<CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponse, CloseGameCategoriesApiStreamsCloseGameCategoriesPostError, Options<CloseGameCategoriesApiStreamsCloseGameCategoriesPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await closeGameCategoriesApiStreamsCloseGameCategoriesPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getNassalStreamsApiNassalStreamsGetQueryKey = (options?: Options<GetNassalStreamsApiNassalStreamsGetData>) => createQueryKey('getNassalStreamsApiNassalStreamsGet', options);

/**
 * Get Nassal Streams
 * Return Nassal players whose main stream is online.
 *
 * Player list and online flags come from the Nassal game API.
 * The first entry in each player's stream array is their main platform.
 * The event judge (Twitch) is added separately with Helix live checks.
 */
export const getNassalStreamsApiNassalStreamsGetOptions = (options?: Options<GetNassalStreamsApiNassalStreamsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getNassalStreamsApiNassalStreamsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getNassalStreamsApiNassalStreamsGetQueryKey(options)
    });
};

export const getEventsApiEventsGetQueryKey = (options?: Options<GetEventsApiEventsGetData>) => createQueryKey('getEventsApiEventsGet', options);

/**
 * Get Events
 */
export const getEventsApiEventsGetOptions = (options?: Options<GetEventsApiEventsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getEventsApiEventsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventsApiEventsGetQueryKey(options)
    });
};

/**
 * Search Emotes
 */
export const searchEmotesApiEmotesSearchPostMutation = (options?: Partial<Options<SearchEmotesApiEmotesSearchPostData>>): MutationOptions<SearchEmotesApiEmotesSearchPostResponse, SearchEmotesApiEmotesSearchPostError, Options<SearchEmotesApiEmotesSearchPostData>> => {
    const mutationOptions: MutationOptions<SearchEmotesApiEmotesSearchPostResponse, SearchEmotesApiEmotesSearchPostError, Options<SearchEmotesApiEmotesSearchPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await searchEmotesApiEmotesSearchPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Send Notification
 */
export const sendNotificationApiNotificationsSendPostMutation = (options?: Partial<Options<SendNotificationApiNotificationsSendPostData>>): MutationOptions<unknown, SendNotificationApiNotificationsSendPostError, Options<SendNotificationApiNotificationsSendPostData>> => {
    const mutationOptions: MutationOptions<unknown, SendNotificationApiNotificationsSendPostError, Options<SendNotificationApiNotificationsSendPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await sendNotificationApiNotificationsSendPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Notify Player Move
 */
export const notifyPlayerMoveApiNotificationsPlayerMovePostMutation = (options?: Partial<Options<NotifyPlayerMoveApiNotificationsPlayerMovePostData>>): MutationOptions<unknown, NotifyPlayerMoveApiNotificationsPlayerMovePostError, Options<NotifyPlayerMoveApiNotificationsPlayerMovePostData>> => {
    const mutationOptions: MutationOptions<unknown, NotifyPlayerMoveApiNotificationsPlayerMovePostError, Options<NotifyPlayerMoveApiNotificationsPlayerMovePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await notifyPlayerMoveApiNotificationsPlayerMovePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Notify Player Online
 */
export const notifyPlayerOnlineApiNotificationsPlayerOnlinePostMutation = (options?: Partial<Options<NotifyPlayerOnlineApiNotificationsPlayerOnlinePostData>>): MutationOptions<unknown, NotifyPlayerOnlineApiNotificationsPlayerOnlinePostError, Options<NotifyPlayerOnlineApiNotificationsPlayerOnlinePostData>> => {
    const mutationOptions: MutationOptions<unknown, NotifyPlayerOnlineApiNotificationsPlayerOnlinePostError, Options<NotifyPlayerOnlineApiNotificationsPlayerOnlinePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await notifyPlayerOnlineApiNotificationsPlayerOnlinePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
