// This file is auto-generated by @hey-api/openapi-ts

import { type Options, loginApiLoginPost, logoutApiLogoutPost, fetchCurrentUserApiUsersCurrentGet, getUsersApiUsersGet, getGamesApiGamesHistoryGet, makeDiceRollApiDiceRollsPost, getRollByIdApiDiceRollsRollIdGet, searchIgdbGamesGetApiIgdbGamesSearchGet, refreshStreamsApiStreamsRefreshPost, getGameDurationApiStreamsGameDurationGet, closeGameCategoriesApiStreamsCloseGameCategoriesPost } from '../sdk.gen';
import { type MutationOptions, queryOptions, type DefaultError } from '@tanstack/svelte-query';
import type { LoginApiLoginPostData, LoginApiLoginPostError, LoginApiLoginPostResponse, LogoutApiLogoutPostData, LogoutApiLogoutPostError, FetchCurrentUserApiUsersCurrentGetData, GetUsersApiUsersGetData, GetGamesApiGamesHistoryGetData, MakeDiceRollApiDiceRollsPostData, MakeDiceRollApiDiceRollsPostError, MakeDiceRollApiDiceRollsPostResponse, GetRollByIdApiDiceRollsRollIdGetData, SearchIgdbGamesGetApiIgdbGamesSearchGetData, RefreshStreamsApiStreamsRefreshPostData, RefreshStreamsApiStreamsRefreshPostResponse, GetGameDurationApiStreamsGameDurationGetData, CloseGameCategoriesApiStreamsCloseGameCategoriesPostData, CloseGameCategoriesApiStreamsCloseGameCategoriesPostError, CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponse } from '../types.gen';
import { client } from '../client.gen';

/**
 * Login
 */
export const loginApiLoginPostMutation = (options?: Partial<Options<LoginApiLoginPostData>>): MutationOptions<LoginApiLoginPostResponse, LoginApiLoginPostError, Options<LoginApiLoginPostData>> => {
    const mutationOptions: MutationOptions<LoginApiLoginPostResponse, LoginApiLoginPostError, Options<LoginApiLoginPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginApiLoginPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const logoutApiLogoutPostMutation = (options?: Partial<Options<LogoutApiLogoutPostData>>): MutationOptions<unknown, LogoutApiLogoutPostError, Options<LogoutApiLogoutPostData>> => {
    const mutationOptions: MutationOptions<unknown, LogoutApiLogoutPostError, Options<LogoutApiLogoutPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutApiLogoutPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const fetchCurrentUserApiUsersCurrentGetQueryKey = (options?: Options<FetchCurrentUserApiUsersCurrentGetData>) => createQueryKey('fetchCurrentUserApiUsersCurrentGet', options);

/**
 * Fetch Current User
 */
export const fetchCurrentUserApiUsersCurrentGetOptions = (options?: Options<FetchCurrentUserApiUsersCurrentGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await fetchCurrentUserApiUsersCurrentGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: fetchCurrentUserApiUsersCurrentGetQueryKey(options)
    });
};

export const getUsersApiUsersGetQueryKey = (options?: Options<GetUsersApiUsersGetData>) => createQueryKey('getUsersApiUsersGet', options);

/**
 * Get Users
 */
export const getUsersApiUsersGetOptions = (options?: Options<GetUsersApiUsersGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUsersApiUsersGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUsersApiUsersGetQueryKey(options)
    });
};

export const getGamesApiGamesHistoryGetQueryKey = (options?: Options<GetGamesApiGamesHistoryGetData>) => createQueryKey('getGamesApiGamesHistoryGet', options);

/**
 * Get Games
 */
export const getGamesApiGamesHistoryGetOptions = (options?: Options<GetGamesApiGamesHistoryGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getGamesApiGamesHistoryGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getGamesApiGamesHistoryGetQueryKey(options)
    });
};

/**
 * Make Dice Roll
 */
export const makeDiceRollApiDiceRollsPostMutation = (options?: Partial<Options<MakeDiceRollApiDiceRollsPostData>>): MutationOptions<MakeDiceRollApiDiceRollsPostResponse, MakeDiceRollApiDiceRollsPostError, Options<MakeDiceRollApiDiceRollsPostData>> => {
    const mutationOptions: MutationOptions<MakeDiceRollApiDiceRollsPostResponse, MakeDiceRollApiDiceRollsPostError, Options<MakeDiceRollApiDiceRollsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await makeDiceRollApiDiceRollsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getRollByIdApiDiceRollsRollIdGetQueryKey = (options: Options<GetRollByIdApiDiceRollsRollIdGetData>) => createQueryKey('getRollByIdApiDiceRollsRollIdGet', options);

/**
 * Get Roll By Id
 */
export const getRollByIdApiDiceRollsRollIdGetOptions = (options: Options<GetRollByIdApiDiceRollsRollIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRollByIdApiDiceRollsRollIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRollByIdApiDiceRollsRollIdGetQueryKey(options)
    });
};

export const searchIgdbGamesGetApiIgdbGamesSearchGetQueryKey = (options: Options<SearchIgdbGamesGetApiIgdbGamesSearchGetData>) => createQueryKey('searchIgdbGamesGetApiIgdbGamesSearchGet', options);

/**
 * Search Igdb Games Get
 */
export const searchIgdbGamesGetApiIgdbGamesSearchGetOptions = (options: Options<SearchIgdbGamesGetApiIgdbGamesSearchGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await searchIgdbGamesGetApiIgdbGamesSearchGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: searchIgdbGamesGetApiIgdbGamesSearchGetQueryKey(options)
    });
};

/**
 * Refresh Streams
 * Refresh stream statuses for all active streamers.
 *
 * Returns statistics about the refresh operation:
 * - total_players: Total number of active players checked
 * - updated_players: Number of players whose status changed
 * - online_players: Number of players currently online
 * - errors: List of error messages if any occurred
 */
export const refreshStreamsApiStreamsRefreshPostMutation = (options?: Partial<Options<RefreshStreamsApiStreamsRefreshPostData>>): MutationOptions<RefreshStreamsApiStreamsRefreshPostResponse, DefaultError, Options<RefreshStreamsApiStreamsRefreshPostData>> => {
    const mutationOptions: MutationOptions<RefreshStreamsApiStreamsRefreshPostResponse, DefaultError, Options<RefreshStreamsApiStreamsRefreshPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refreshStreamsApiStreamsRefreshPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getGameDurationApiStreamsGameDurationGetQueryKey = (options: Options<GetGameDurationApiStreamsGameDurationGetData>) => createQueryKey('getGameDurationApiStreamsGameDurationGet', options);

/**
 * Get Game Duration
 * Get total duration of all open categories for a specific game within active event.
 *
 * Used by aukus-backend when creating a player move to calculate item_duration.
 *
 * Returns:
 * - duration: Total seconds of all open category sessions
 * - sessions_count: Number of open sessions
 * - event_slug: Slug of the active event (if any)
 */
export const getGameDurationApiStreamsGameDurationGetOptions = (options: Options<GetGameDurationApiStreamsGameDurationGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getGameDurationApiStreamsGameDurationGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getGameDurationApiStreamsGameDurationGetQueryKey(options)
    });
};

/**
 * Close Game Categories
 * Close all open categories for a specific game within active event.
 *
 * Called by aukus-backend after creating a player move to mark the game session as complete.
 * This ensures that if the player starts the same game again, the timer resets.
 *
 * Request body:
 * - slug: User slug
 * - game_name: Name of the game to close categories for
 *
 * Returns:
 * - status: Operation status
 * - closed: Number of categories closed
 * - game_name: Name of the game
 * - event_slug: Slug of the active event (if any)
 */
export const closeGameCategoriesApiStreamsCloseGameCategoriesPostMutation = (options?: Partial<Options<CloseGameCategoriesApiStreamsCloseGameCategoriesPostData>>): MutationOptions<CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponse, CloseGameCategoriesApiStreamsCloseGameCategoriesPostError, Options<CloseGameCategoriesApiStreamsCloseGameCategoriesPostData>> => {
    const mutationOptions: MutationOptions<CloseGameCategoriesApiStreamsCloseGameCategoriesPostResponse, CloseGameCategoriesApiStreamsCloseGameCategoriesPostError, Options<CloseGameCategoriesApiStreamsCloseGameCategoriesPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await closeGameCategoriesApiStreamsCloseGameCategoriesPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
