// This file is auto-generated by @hey-api/openapi-ts

import { type Options, getCanvasFilesApiCanvasPlayerSlugGet, uploadCanvasImageApiCanvasPlayerSlugUploadPost, updateCanvasApiCanvasPlayerSlugUpdatePut, getEventDataApiEventDataGet, playerStatsApiPlayersStatsGet, makePlayerMoveApiPlayersMovePost } from '../sdk.gen';
import { queryOptions, type MutationOptions } from '@tanstack/svelte-query';
import type { GetCanvasFilesApiCanvasPlayerSlugGetData, UploadCanvasImageApiCanvasPlayerSlugUploadPostData, UploadCanvasImageApiCanvasPlayerSlugUploadPostError, UploadCanvasImageApiCanvasPlayerSlugUploadPostResponse, UpdateCanvasApiCanvasPlayerSlugUpdatePutData, UpdateCanvasApiCanvasPlayerSlugUpdatePutError, UpdateCanvasApiCanvasPlayerSlugUpdatePutResponse, GetEventDataApiEventDataGetData, PlayerStatsApiPlayersStatsGetData, MakePlayerMoveApiPlayersMovePostData, MakePlayerMoveApiPlayersMovePostError, MakePlayerMoveApiPlayersMovePostResponse } from '../types.gen';
import { client } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getCanvasFilesApiCanvasPlayerSlugGetQueryKey = (options: Options<GetCanvasFilesApiCanvasPlayerSlugGetData>) => createQueryKey('getCanvasFilesApiCanvasPlayerSlugGet', options);

/**
 * Get Canvas Files
 */
export const getCanvasFilesApiCanvasPlayerSlugGetOptions = (options: Options<GetCanvasFilesApiCanvasPlayerSlugGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCanvasFilesApiCanvasPlayerSlugGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCanvasFilesApiCanvasPlayerSlugGetQueryKey(options)
    });
};

/**
 * Upload Canvas Image
 */
export const uploadCanvasImageApiCanvasPlayerSlugUploadPostMutation = (options?: Partial<Options<UploadCanvasImageApiCanvasPlayerSlugUploadPostData>>): MutationOptions<UploadCanvasImageApiCanvasPlayerSlugUploadPostResponse, UploadCanvasImageApiCanvasPlayerSlugUploadPostError, Options<UploadCanvasImageApiCanvasPlayerSlugUploadPostData>> => {
    const mutationOptions: MutationOptions<UploadCanvasImageApiCanvasPlayerSlugUploadPostResponse, UploadCanvasImageApiCanvasPlayerSlugUploadPostError, Options<UploadCanvasImageApiCanvasPlayerSlugUploadPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadCanvasImageApiCanvasPlayerSlugUploadPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Canvas
 */
export const updateCanvasApiCanvasPlayerSlugUpdatePutMutation = (options?: Partial<Options<UpdateCanvasApiCanvasPlayerSlugUpdatePutData>>): MutationOptions<UpdateCanvasApiCanvasPlayerSlugUpdatePutResponse, UpdateCanvasApiCanvasPlayerSlugUpdatePutError, Options<UpdateCanvasApiCanvasPlayerSlugUpdatePutData>> => {
    const mutationOptions: MutationOptions<UpdateCanvasApiCanvasPlayerSlugUpdatePutResponse, UpdateCanvasApiCanvasPlayerSlugUpdatePutError, Options<UpdateCanvasApiCanvasPlayerSlugUpdatePutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateCanvasApiCanvasPlayerSlugUpdatePut({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEventDataApiEventDataGetQueryKey = (options?: Options<GetEventDataApiEventDataGetData>) => createQueryKey('getEventDataApiEventDataGet', options);

/**
 * Get Event Data
 */
export const getEventDataApiEventDataGetOptions = (options?: Options<GetEventDataApiEventDataGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getEventDataApiEventDataGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventDataApiEventDataGetQueryKey(options)
    });
};

export const playerStatsApiPlayersStatsGetQueryKey = (options?: Options<PlayerStatsApiPlayersStatsGetData>) => createQueryKey('playerStatsApiPlayersStatsGet', options);

/**
 * Player Stats
 */
export const playerStatsApiPlayersStatsGetOptions = (options?: Options<PlayerStatsApiPlayersStatsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await playerStatsApiPlayersStatsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: playerStatsApiPlayersStatsGetQueryKey(options)
    });
};

/**
 * Make Player Move
 */
export const makePlayerMoveApiPlayersMovePostMutation = (options?: Partial<Options<MakePlayerMoveApiPlayersMovePostData>>): MutationOptions<MakePlayerMoveApiPlayersMovePostResponse, MakePlayerMoveApiPlayersMovePostError, Options<MakePlayerMoveApiPlayersMovePostData>> => {
    const mutationOptions: MutationOptions<MakePlayerMoveApiPlayersMovePostResponse, MakePlayerMoveApiPlayersMovePostError, Options<MakePlayerMoveApiPlayersMovePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await makePlayerMoveApiPlayersMovePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
