// This file is auto-generated by @hey-api/openapi-ts

import { type Options, getCanvasFilesApiCanvasPlayerSlugGet, uploadCanvasImageApiCanvasPlayerSlugUploadPost, updateCanvasApiCanvasPlayerSlugUpdatePut, getEventDataApiEventDataGet, getDonationsApiDonationsGet, playerStatsApiPlayersStatsGet, createPlayerMoveApiPlayersMovePost, finishPlayerMoveApiPlayersMoveFinishPost, getPlayerMovesApiPlayersMovesGet, setPlayerSkinsApiPlayersSkinsPost, kickPlayerApiPlayersKickPost, addShitApiPlayersAddShitPost, makeShieldApiPlayersMakeShieldPost, getUnlockableSkinsApiPlayersUnlockableSkinsGet, unlockSkinApiPlayersUnlockSkinPost, updatePlayerMoveApiPlayersMovesMoveIdPatch, getCurrentRulesVersionApiRulesCurrentGet, getAllRulesVersionsApiRulesGet, createNewRulesVersionApiRulesPost } from '../sdk.gen';
import { queryOptions, type MutationOptions } from '@tanstack/svelte-query';
import type { GetCanvasFilesApiCanvasPlayerSlugGetData, UploadCanvasImageApiCanvasPlayerSlugUploadPostData, UploadCanvasImageApiCanvasPlayerSlugUploadPostError, UploadCanvasImageApiCanvasPlayerSlugUploadPostResponse, UpdateCanvasApiCanvasPlayerSlugUpdatePutData, UpdateCanvasApiCanvasPlayerSlugUpdatePutError, UpdateCanvasApiCanvasPlayerSlugUpdatePutResponse, GetEventDataApiEventDataGetData, GetDonationsApiDonationsGetData, PlayerStatsApiPlayersStatsGetData, CreatePlayerMoveApiPlayersMovePostData, CreatePlayerMoveApiPlayersMovePostError, CreatePlayerMoveApiPlayersMovePostResponse, FinishPlayerMoveApiPlayersMoveFinishPostData, FinishPlayerMoveApiPlayersMoveFinishPostError, FinishPlayerMoveApiPlayersMoveFinishPostResponse, GetPlayerMovesApiPlayersMovesGetData, SetPlayerSkinsApiPlayersSkinsPostData, SetPlayerSkinsApiPlayersSkinsPostError, KickPlayerApiPlayersKickPostData, KickPlayerApiPlayersKickPostError, KickPlayerApiPlayersKickPostResponse, AddShitApiPlayersAddShitPostData, AddShitApiPlayersAddShitPostError, MakeShieldApiPlayersMakeShieldPostData, MakeShieldApiPlayersMakeShieldPostError, GetUnlockableSkinsApiPlayersUnlockableSkinsGetData, UnlockSkinApiPlayersUnlockSkinPostData, UnlockSkinApiPlayersUnlockSkinPostError, UpdatePlayerMoveApiPlayersMovesMoveIdPatchData, UpdatePlayerMoveApiPlayersMovesMoveIdPatchError, GetCurrentRulesVersionApiRulesCurrentGetData, GetAllRulesVersionsApiRulesGetData, CreateNewRulesVersionApiRulesPostData, CreateNewRulesVersionApiRulesPostError } from '../types.gen';
import { client } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getCanvasFilesApiCanvasPlayerSlugGetQueryKey = (options: Options<GetCanvasFilesApiCanvasPlayerSlugGetData>) => createQueryKey('getCanvasFilesApiCanvasPlayerSlugGet', options);

/**
 * Get Canvas Files
 */
export const getCanvasFilesApiCanvasPlayerSlugGetOptions = (options: Options<GetCanvasFilesApiCanvasPlayerSlugGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCanvasFilesApiCanvasPlayerSlugGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCanvasFilesApiCanvasPlayerSlugGetQueryKey(options)
    });
};

/**
 * Upload Canvas Image
 */
export const uploadCanvasImageApiCanvasPlayerSlugUploadPostMutation = (options?: Partial<Options<UploadCanvasImageApiCanvasPlayerSlugUploadPostData>>): MutationOptions<UploadCanvasImageApiCanvasPlayerSlugUploadPostResponse, UploadCanvasImageApiCanvasPlayerSlugUploadPostError, Options<UploadCanvasImageApiCanvasPlayerSlugUploadPostData>> => {
    const mutationOptions: MutationOptions<UploadCanvasImageApiCanvasPlayerSlugUploadPostResponse, UploadCanvasImageApiCanvasPlayerSlugUploadPostError, Options<UploadCanvasImageApiCanvasPlayerSlugUploadPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadCanvasImageApiCanvasPlayerSlugUploadPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Canvas
 */
export const updateCanvasApiCanvasPlayerSlugUpdatePutMutation = (options?: Partial<Options<UpdateCanvasApiCanvasPlayerSlugUpdatePutData>>): MutationOptions<UpdateCanvasApiCanvasPlayerSlugUpdatePutResponse, UpdateCanvasApiCanvasPlayerSlugUpdatePutError, Options<UpdateCanvasApiCanvasPlayerSlugUpdatePutData>> => {
    const mutationOptions: MutationOptions<UpdateCanvasApiCanvasPlayerSlugUpdatePutResponse, UpdateCanvasApiCanvasPlayerSlugUpdatePutError, Options<UpdateCanvasApiCanvasPlayerSlugUpdatePutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateCanvasApiCanvasPlayerSlugUpdatePut({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEventDataApiEventDataGetQueryKey = (options?: Options<GetEventDataApiEventDataGetData>) => createQueryKey('getEventDataApiEventDataGet', options);

/**
 * Get Event Data
 */
export const getEventDataApiEventDataGetOptions = (options?: Options<GetEventDataApiEventDataGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getEventDataApiEventDataGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventDataApiEventDataGetQueryKey(options)
    });
};

export const getDonationsApiDonationsGetQueryKey = (options?: Options<GetDonationsApiDonationsGetData>) => createQueryKey('getDonationsApiDonationsGet', options);

/**
 * Get Donations
 */
export const getDonationsApiDonationsGetOptions = (options?: Options<GetDonationsApiDonationsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDonationsApiDonationsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getDonationsApiDonationsGetQueryKey(options)
    });
};

export const playerStatsApiPlayersStatsGetQueryKey = (options?: Options<PlayerStatsApiPlayersStatsGetData>) => createQueryKey('playerStatsApiPlayersStatsGet', options);

/**
 * Player Stats
 */
export const playerStatsApiPlayersStatsGetOptions = (options?: Options<PlayerStatsApiPlayersStatsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await playerStatsApiPlayersStatsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: playerStatsApiPlayersStatsGetQueryKey(options)
    });
};

/**
 * Create Player Move
 */
export const createPlayerMoveApiPlayersMovePostMutation = (options?: Partial<Options<CreatePlayerMoveApiPlayersMovePostData>>): MutationOptions<CreatePlayerMoveApiPlayersMovePostResponse, CreatePlayerMoveApiPlayersMovePostError, Options<CreatePlayerMoveApiPlayersMovePostData>> => {
    const mutationOptions: MutationOptions<CreatePlayerMoveApiPlayersMovePostResponse, CreatePlayerMoveApiPlayersMovePostError, Options<CreatePlayerMoveApiPlayersMovePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPlayerMoveApiPlayersMovePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Finish Player Move
 */
export const finishPlayerMoveApiPlayersMoveFinishPostMutation = (options?: Partial<Options<FinishPlayerMoveApiPlayersMoveFinishPostData>>): MutationOptions<FinishPlayerMoveApiPlayersMoveFinishPostResponse, FinishPlayerMoveApiPlayersMoveFinishPostError, Options<FinishPlayerMoveApiPlayersMoveFinishPostData>> => {
    const mutationOptions: MutationOptions<FinishPlayerMoveApiPlayersMoveFinishPostResponse, FinishPlayerMoveApiPlayersMoveFinishPostError, Options<FinishPlayerMoveApiPlayersMoveFinishPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await finishPlayerMoveApiPlayersMoveFinishPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPlayerMovesApiPlayersMovesGetQueryKey = (options?: Options<GetPlayerMovesApiPlayersMovesGetData>) => createQueryKey('getPlayerMovesApiPlayersMovesGet', options);

/**
 * Get Player Moves
 */
export const getPlayerMovesApiPlayersMovesGetOptions = (options?: Options<GetPlayerMovesApiPlayersMovesGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPlayerMovesApiPlayersMovesGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPlayerMovesApiPlayersMovesGetQueryKey(options)
    });
};

/**
 * Set Player Skins
 */
export const setPlayerSkinsApiPlayersSkinsPostMutation = (options?: Partial<Options<SetPlayerSkinsApiPlayersSkinsPostData>>): MutationOptions<unknown, SetPlayerSkinsApiPlayersSkinsPostError, Options<SetPlayerSkinsApiPlayersSkinsPostData>> => {
    const mutationOptions: MutationOptions<unknown, SetPlayerSkinsApiPlayersSkinsPostError, Options<SetPlayerSkinsApiPlayersSkinsPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await setPlayerSkinsApiPlayersSkinsPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Kick Player
 */
export const kickPlayerApiPlayersKickPostMutation = (options?: Partial<Options<KickPlayerApiPlayersKickPostData>>): MutationOptions<KickPlayerApiPlayersKickPostResponse, KickPlayerApiPlayersKickPostError, Options<KickPlayerApiPlayersKickPostData>> => {
    const mutationOptions: MutationOptions<KickPlayerApiPlayersKickPostResponse, KickPlayerApiPlayersKickPostError, Options<KickPlayerApiPlayersKickPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await kickPlayerApiPlayersKickPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Add Shit
 */
export const addShitApiPlayersAddShitPostMutation = (options?: Partial<Options<AddShitApiPlayersAddShitPostData>>): MutationOptions<unknown, AddShitApiPlayersAddShitPostError, Options<AddShitApiPlayersAddShitPostData>> => {
    const mutationOptions: MutationOptions<unknown, AddShitApiPlayersAddShitPostError, Options<AddShitApiPlayersAddShitPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addShitApiPlayersAddShitPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Make Shield
 */
export const makeShieldApiPlayersMakeShieldPostMutation = (options?: Partial<Options<MakeShieldApiPlayersMakeShieldPostData>>): MutationOptions<unknown, MakeShieldApiPlayersMakeShieldPostError, Options<MakeShieldApiPlayersMakeShieldPostData>> => {
    const mutationOptions: MutationOptions<unknown, MakeShieldApiPlayersMakeShieldPostError, Options<MakeShieldApiPlayersMakeShieldPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await makeShieldApiPlayersMakeShieldPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUnlockableSkinsApiPlayersUnlockableSkinsGetQueryKey = (options?: Options<GetUnlockableSkinsApiPlayersUnlockableSkinsGetData>) => createQueryKey('getUnlockableSkinsApiPlayersUnlockableSkinsGet', options);

/**
 * Get Unlockable Skins
 */
export const getUnlockableSkinsApiPlayersUnlockableSkinsGetOptions = (options?: Options<GetUnlockableSkinsApiPlayersUnlockableSkinsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getUnlockableSkinsApiPlayersUnlockableSkinsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUnlockableSkinsApiPlayersUnlockableSkinsGetQueryKey(options)
    });
};

/**
 * Unlock Skin
 */
export const unlockSkinApiPlayersUnlockSkinPostMutation = (options?: Partial<Options<UnlockSkinApiPlayersUnlockSkinPostData>>): MutationOptions<unknown, UnlockSkinApiPlayersUnlockSkinPostError, Options<UnlockSkinApiPlayersUnlockSkinPostData>> => {
    const mutationOptions: MutationOptions<unknown, UnlockSkinApiPlayersUnlockSkinPostError, Options<UnlockSkinApiPlayersUnlockSkinPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await unlockSkinApiPlayersUnlockSkinPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Player Move
 */
export const updatePlayerMoveApiPlayersMovesMoveIdPatchMutation = (options?: Partial<Options<UpdatePlayerMoveApiPlayersMovesMoveIdPatchData>>): MutationOptions<unknown, UpdatePlayerMoveApiPlayersMovesMoveIdPatchError, Options<UpdatePlayerMoveApiPlayersMovesMoveIdPatchData>> => {
    const mutationOptions: MutationOptions<unknown, UpdatePlayerMoveApiPlayersMovesMoveIdPatchError, Options<UpdatePlayerMoveApiPlayersMovesMoveIdPatchData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updatePlayerMoveApiPlayersMovesMoveIdPatch({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCurrentRulesVersionApiRulesCurrentGetQueryKey = (options?: Options<GetCurrentRulesVersionApiRulesCurrentGetData>) => createQueryKey('getCurrentRulesVersionApiRulesCurrentGet', options);

/**
 * Get Current Rules Version
 */
export const getCurrentRulesVersionApiRulesCurrentGetOptions = (options?: Options<GetCurrentRulesVersionApiRulesCurrentGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCurrentRulesVersionApiRulesCurrentGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCurrentRulesVersionApiRulesCurrentGetQueryKey(options)
    });
};

export const getAllRulesVersionsApiRulesGetQueryKey = (options?: Options<GetAllRulesVersionsApiRulesGetData>) => createQueryKey('getAllRulesVersionsApiRulesGet', options);

/**
 * Get All Rules Versions
 */
export const getAllRulesVersionsApiRulesGetOptions = (options?: Options<GetAllRulesVersionsApiRulesGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAllRulesVersionsApiRulesGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAllRulesVersionsApiRulesGetQueryKey(options)
    });
};

/**
 * Create New Rules Version
 */
export const createNewRulesVersionApiRulesPostMutation = (options?: Partial<Options<CreateNewRulesVersionApiRulesPostData>>): MutationOptions<unknown, CreateNewRulesVersionApiRulesPostError, Options<CreateNewRulesVersionApiRulesPostData>> => {
    const mutationOptions: MutationOptions<unknown, CreateNewRulesVersionApiRulesPostError, Options<CreateNewRulesVersionApiRulesPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createNewRulesVersionApiRulesPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
