// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type Client, type TDataShape, formDataBodySerializer } from './client';
import type { GetCanvasFilesApiCanvasPlayerSlugGetData, GetCanvasFilesApiCanvasPlayerSlugGetResponses, GetCanvasFilesApiCanvasPlayerSlugGetErrors, UploadCanvasImageApiCanvasPlayerSlugUploadPostData, UploadCanvasImageApiCanvasPlayerSlugUploadPostResponses, UploadCanvasImageApiCanvasPlayerSlugUploadPostErrors, UpdateCanvasApiCanvasPlayerSlugUpdatePutData, UpdateCanvasApiCanvasPlayerSlugUpdatePutResponses, UpdateCanvasApiCanvasPlayerSlugUpdatePutErrors, GetEventDataApiEventDataGetData, GetEventDataApiEventDataGetResponses, GetEventDataApiEventDataGetErrors, PlayerStatsApiPlayersStatsGetData, PlayerStatsApiPlayersStatsGetResponses, MakePlayerMoveApiPlayersMovePostData, MakePlayerMoveApiPlayersMovePostResponses, MakePlayerMoveApiPlayersMovePostErrors } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Canvas Files
 */
export const getCanvasFilesApiCanvasPlayerSlugGet = <ThrowOnError extends boolean = false>(options: Options<GetCanvasFilesApiCanvasPlayerSlugGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetCanvasFilesApiCanvasPlayerSlugGetResponses, GetCanvasFilesApiCanvasPlayerSlugGetErrors, ThrowOnError>({
        url: '/api/canvas/{player_slug}',
        ...options
    });
};

/**
 * Upload Canvas Image
 */
export const uploadCanvasImageApiCanvasPlayerSlugUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadCanvasImageApiCanvasPlayerSlugUploadPostData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadCanvasImageApiCanvasPlayerSlugUploadPostResponses, UploadCanvasImageApiCanvasPlayerSlugUploadPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/canvas/{player_slug}/upload',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Update Canvas
 */
export const updateCanvasApiCanvasPlayerSlugUpdatePut = <ThrowOnError extends boolean = false>(options: Options<UpdateCanvasApiCanvasPlayerSlugUpdatePutData, ThrowOnError>) => {
    return (options.client ?? client).put<UpdateCanvasApiCanvasPlayerSlugUpdatePutResponses, UpdateCanvasApiCanvasPlayerSlugUpdatePutErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/canvas/{player_slug}/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Event Data
 */
export const getEventDataApiEventDataGet = <ThrowOnError extends boolean = false>(options?: Options<GetEventDataApiEventDataGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEventDataApiEventDataGetResponses, GetEventDataApiEventDataGetErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/event_data',
        ...options
    });
};

/**
 * Player Stats
 */
export const playerStatsApiPlayersStatsGet = <ThrowOnError extends boolean = false>(options?: Options<PlayerStatsApiPlayersStatsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<PlayerStatsApiPlayersStatsGetResponses, unknown, ThrowOnError>({
        url: '/api/players/stats',
        ...options
    });
};

/**
 * Make Player Move
 */
export const makePlayerMoveApiPlayersMovePost = <ThrowOnError extends boolean = false>(options: Options<MakePlayerMoveApiPlayersMovePostData, ThrowOnError>) => {
    return (options.client ?? client).post<MakePlayerMoveApiPlayersMovePostResponses, MakePlayerMoveApiPlayersMovePostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/players/move',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
