// This file is auto-generated by @hey-api/openapi-ts

/**
 * AchievementItem
 */
export type AchievementItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Description
     */
    description: string;
    /**
     * Reward Skin Id
     */
    reward_skin_id: number;
};

/**
 * Body_upload_canvas_image_api_canvas__player_slug__upload_post
 */
export type BodyUploadCanvasImageApiCanvasPlayerSlugUploadPost = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
};

/**
 * CanvasFile
 */
export type CanvasFile = {
    /**
     * Id
     */
    id: number;
    /**
     * Rotation
     */
    rotation: number;
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * Url
     */
    url: string;
    /**
     * Width
     */
    width: number;
    /**
     * Height
     */
    height: number;
    /**
     * Zindex
     */
    zIndex: number;
    /**
     * Scalex
     */
    scaleX: number;
    /**
     * Scaley
     */
    scaleY: number;
};

/**
 * CanvasFilesResponse
 */
export type CanvasFilesResponse = {
    /**
     * Files
     */
    files: Array<CanvasFile>;
};

/**
 * CanvasUpdateRequest
 */
export type CanvasUpdateRequest = {
    /**
     * Files
     */
    files: Array<CanvasFile>;
    /**
     * Delete Ids
     */
    delete_ids?: Array<number> | null;
};

/**
 * EventDataResponse
 */
export type EventDataResponse = {
    /**
     * Players
     */
    players: Array<PlayerItem>;
    /**
     * Event Settings
     */
    event_settings: {
        [key: string]: string | number | null;
    };
    /**
     * Skins
     */
    skins: Array<SkinItem>;
    /**
     * Achievements
     */
    achievements: Array<AchievementItem>;
    my_last_move: PlayerMoveItem | null;
};

/**
 * GameDifficulty
 */
export type GameDifficulty = -1 | 0 | 1 | 2;

/**
 * GameLength
 */
export type GameLength = '0-3' | '3-5' | '5-10' | '10-20' | '20-25' | '25+';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PlayerItem
 */
export type PlayerItem = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Map Position
     */
    map_position: number;
    /**
     * Equipped Skins
     */
    equipped_skins: Array<number>;
    /**
     * Unlocked Achievements
     */
    unlocked_achievements: Array<UnlockedAchievementItem>;
};

/**
 * PlayerMoveItem
 */
export type PlayerMoveItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
    /**
     * Player Slug
     */
    player_slug: string;
    type: PlayerMoveType;
    /**
     * Item Title
     */
    item_title: string;
    /**
     * Item Duration
     */
    item_duration: number;
    /**
     * Item Review
     */
    item_review: string;
    /**
     * Item Rating
     */
    item_rating: number;
    item_length: GameLength;
    /**
     * Vod Links
     */
    vod_links: string | null;
    /**
     * Game Id
     */
    game_id: number | null;
    difficulty_level: GameDifficulty;
    /**
     * Cell From
     */
    cell_from: number;
    /**
     * Cell To
     */
    cell_to: number;
    /**
     * Ladder From
     */
    ladder_from: number | null;
    /**
     * Ladder To
     */
    ladder_to: number | null;
    /**
     * Snake From
     */
    snake_from: number | null;
    /**
     * Snake To
     */
    snake_to: number | null;
    /**
     * Dice Roll Id
     */
    dice_roll_id: number | null;
    /**
     * Dice Roll Sum
     */
    dice_roll_sum: number | null;
    /**
     * Dice Roll
     */
    dice_roll: string | null;
};

/**
 * PlayerMoveRequest
 */
export type PlayerMoveRequest = {
    type: PlayerMoveType;
    /**
     * Item Title
     */
    item_title: string;
    item_length: GameLength | null;
    /**
     * Item Review
     */
    item_review: string;
    /**
     * Item Rating
     */
    item_rating: number | null;
    /**
     * Game Id
     */
    game_id: number | null;
    difficulty: GameDifficulty | null;
    /**
     * Dice Roll Id
     */
    dice_roll_id: number | null;
};

/**
 * PlayerMoveResponse
 */
export type PlayerMoveResponse = {
    /**
     * Move Id
     */
    move_id: number;
    /**
     * Move To
     */
    move_to: number;
    /**
     * Snake To
     */
    snake_to: number | null;
    /**
     * Ladder To
     */
    ladder_to: number | null;
};

/**
 * PlayerMoveType
 */
export type PlayerMoveType = 'completed' | 'reroll' | 'drop' | 'movie' | 'sheikh_moment';

/**
 * PlayerStatsItem
 */
export type PlayerStatsItem = {
    /**
     * Player Slug
     */
    player_slug: string;
    /**
     * Map Position
     */
    map_position: number;
    /**
     * Total Moves
     */
    total_moves: number;
    /**
     * Games Completed
     */
    games_completed: number;
    /**
     * Games Dropped
     */
    games_dropped: number;
    /**
     * Sheikh Moments
     */
    sheikh_moments: number;
    /**
     * Rerolls
     */
    rerolls: number;
    /**
     * Movies
     */
    movies: number;
    /**
     * Ladders
     */
    ladders: number;
    /**
     * Snakes
     */
    snakes: number;
    /**
     * Tiny Games
     */
    tiny_games: number;
    /**
     * Short Games
     */
    short_games: number;
    /**
     * Medium Games
     */
    medium_games: number;
    /**
     * Long Games
     */
    long_games: number;
    /**
     * Average Dice Roll
     */
    average_dice_roll: number;
    /**
     * Average Move
     */
    average_move: number;
    /**
     * Ladders Moves Sum
     */
    ladders_moves_sum: number;
    /**
     * Snakes Moves Sum
     */
    snakes_moves_sum: number;
};

/**
 * PlayerStatsResponse
 */
export type PlayerStatsResponse = {
    /**
     * Players
     */
    players: Array<PlayerStatsItem>;
};

/**
 * SkinItem
 */
export type SkinItem = {
    /**
     * Id
     */
    id: number;
    slot: SkinSlot;
    /**
     * Image Url
     */
    image_url: string;
};

/**
 * SkinSlot
 */
export type SkinSlot = 'head' | 'body' | 'side';

/**
 * UnlockedAchievementItem
 */
export type UnlockedAchievementItem = {
    /**
     * Id
     */
    id: number;
    /**
     * Unlocked At
     */
    unlocked_at: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetCanvasFilesApiCanvasPlayerSlugGetData = {
    body?: never;
    path: {
        /**
         * Player Slug
         */
        player_slug: string;
    };
    query?: never;
    url: '/api/canvas/{player_slug}';
};

export type GetCanvasFilesApiCanvasPlayerSlugGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCanvasFilesApiCanvasPlayerSlugGetError = GetCanvasFilesApiCanvasPlayerSlugGetErrors[keyof GetCanvasFilesApiCanvasPlayerSlugGetErrors];

export type GetCanvasFilesApiCanvasPlayerSlugGetResponses = {
    /**
     * Successful Response
     */
    200: CanvasFilesResponse;
};

export type GetCanvasFilesApiCanvasPlayerSlugGetResponse = GetCanvasFilesApiCanvasPlayerSlugGetResponses[keyof GetCanvasFilesApiCanvasPlayerSlugGetResponses];

export type UploadCanvasImageApiCanvasPlayerSlugUploadPostData = {
    body: BodyUploadCanvasImageApiCanvasPlayerSlugUploadPost;
    path: {
        /**
         * Player Slug
         */
        player_slug: string;
    };
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/canvas/{player_slug}/upload';
};

export type UploadCanvasImageApiCanvasPlayerSlugUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadCanvasImageApiCanvasPlayerSlugUploadPostError = UploadCanvasImageApiCanvasPlayerSlugUploadPostErrors[keyof UploadCanvasImageApiCanvasPlayerSlugUploadPostErrors];

export type UploadCanvasImageApiCanvasPlayerSlugUploadPostResponses = {
    /**
     * Successful Response
     */
    201: CanvasFile;
};

export type UploadCanvasImageApiCanvasPlayerSlugUploadPostResponse = UploadCanvasImageApiCanvasPlayerSlugUploadPostResponses[keyof UploadCanvasImageApiCanvasPlayerSlugUploadPostResponses];

export type UpdateCanvasApiCanvasPlayerSlugUpdatePutData = {
    body: CanvasUpdateRequest;
    path: {
        /**
         * Player Slug
         */
        player_slug: string;
    };
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/canvas/{player_slug}/update';
};

export type UpdateCanvasApiCanvasPlayerSlugUpdatePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCanvasApiCanvasPlayerSlugUpdatePutError = UpdateCanvasApiCanvasPlayerSlugUpdatePutErrors[keyof UpdateCanvasApiCanvasPlayerSlugUpdatePutErrors];

export type UpdateCanvasApiCanvasPlayerSlugUpdatePutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UpdateCanvasApiCanvasPlayerSlugUpdatePutResponse = UpdateCanvasApiCanvasPlayerSlugUpdatePutResponses[keyof UpdateCanvasApiCanvasPlayerSlugUpdatePutResponses];

export type GetEventDataApiEventDataGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/event_data';
};

export type GetEventDataApiEventDataGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventDataApiEventDataGetError = GetEventDataApiEventDataGetErrors[keyof GetEventDataApiEventDataGetErrors];

export type GetEventDataApiEventDataGetResponses = {
    /**
     * Successful Response
     */
    200: EventDataResponse;
};

export type GetEventDataApiEventDataGetResponse = GetEventDataApiEventDataGetResponses[keyof GetEventDataApiEventDataGetResponses];

export type PlayerStatsApiPlayersStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/players/stats';
};

export type PlayerStatsApiPlayersStatsGetResponses = {
    /**
     * Successful Response
     */
    200: PlayerStatsResponse;
};

export type PlayerStatsApiPlayersStatsGetResponse = PlayerStatsApiPlayersStatsGetResponses[keyof PlayerStatsApiPlayersStatsGetResponses];

export type MakePlayerMoveApiPlayersMovePostData = {
    body: PlayerMoveRequest;
    path?: never;
    query?: {
        /**
         * For Update
         */
        for_update?: boolean;
        /**
         * Allow Acting
         */
        allow_acting?: boolean;
    };
    url: '/api/players/move';
};

export type MakePlayerMoveApiPlayersMovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MakePlayerMoveApiPlayersMovePostError = MakePlayerMoveApiPlayersMovePostErrors[keyof MakePlayerMoveApiPlayersMovePostErrors];

export type MakePlayerMoveApiPlayersMovePostResponses = {
    /**
     * Successful Response
     */
    200: PlayerMoveResponse;
};

export type MakePlayerMoveApiPlayersMovePostResponse = MakePlayerMoveApiPlayersMovePostResponses[keyof MakePlayerMoveApiPlayersMovePostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8301' | (string & {});
};
